### ISSUE TITLE
Toggle control pattern(s)

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#1094]
Our PWA signup button (shown below articles) has two states for before and after notifications are active:

<img width="793" alt="Screen Shot 2020-12-15 at 10 15 08 AM" src="https://user-images.githubusercontent.com/69633/102257073-152fda80-3ec1-11eb-8a6a-e8c36f259b85.png">

<img width="791" alt="Screen Shot 2020-12-15 at 10 15 02 AM" src="https://user-images.githubusercontent.com/69633/102257087-1a8d2500-3ec1-11eb-9e50-c7ca2fb6c14a.png">

This design is fine (it re-uses some of our existing modifiers and other classes), but I can't help but think it might be a more elegant solution if we had a built-in pattern for this sort of thing that included built-in toggles for "on," "off" and maybe an in-between loading/processing state?

This may require more discussion to validate.

**Comment by tylersticka** [comment]
Very relevant article: https://adrianroselli.com/2021/01/multi-function-button.html

(Hat tip to @spaceninja's [Friday Front-End](https://www.getrevue.co/profile/fridayfrontend/issues/friday-front-end-issue-278-the-devil-s-albatross-plus-responsive-html-video-multi-function-buttons-performance-and-more-308375))

**Comment by gerardo-rodriguez** [comment]
> but I can't help but think it might be a more elegant solution if we had a built-in pattern for this sort of thing that included built-in toggles for "on," "off" and maybe an in-between loading/processing state?

Interesting!

@tylersticka I'd have to look at how the notifications button is implemented but I think it only has an "on" and "off" state. Was there an example you found on our site where the in-between loading/processing state exists? 

I'm still doing research to better understand the best way to create the most inclusive UX, but I believe depending on whether or not we need an in-between loading/processing state will impact the implementation.

**Comment by tylersticka** [comment]
> Was there an example you found on our site where the in-between loading/processing state exists?

I'll admit I don't 100% remember what the sequence of events is for our notification subscription. If there's never a "waiting" state, then this isn't necessary now.

**Comment by gerardo-rodriguez** [comment]
> I'll admit I don't 100% remember what the sequence of events is for our notification subscription. If there's never a "waiting" state, then this isn't necessary now.

After further research, I found there are only two states. There are two different notification buttons (one to turn on, the other to turn off notifications), their visibility gets toggled via adding/removing `u-hidden`.

**Comment by gerardo-rodriguez** [comment]
I think I'll approach this by creating an `icon-button` component first. Then I'll add a `toggle` property to allow it to toggle between two states. I'll have to think about the JS a bit more but one option is to fire events to hook into so that you can do as needed when toggled on/off.

**Comment by tylersticka** [comment]
@gerardo-rodriguez That sounds good! The one thing I might suggest is maybe thinking about extending the existing `c-button` CSS component to support icons. Unlike a recent project where Icon Buttons differed significantly from Buttons, these buttons are visually consistent with other buttons on the site… it's mostly their behavior that seems different.

(Happy to discuss with voices if that's confusing!)

**Comment by gerardo-rodriguez** [comment]
> The one thing I might suggest is maybe thinking about extending the existing `c-button` CSS component to support icons. Unlike a recent project where Icon Buttons differed significantly from Buttons, these buttons are visually consistent with other buttons on the site… it's mostly their behavior that seems different.

@tylersticka Good idea!

One possibility could be adding a slot to pass in an icon? Is this sort of along the lines that you were thinking?

> (Happy to discuss with voices if that's confusing!)

If my understanding is _way_ off, I'm more than happy to discuss with voices. 🙂

**Comment by tylersticka** [comment]
> One possibility could be adding a slot to pass in an icon? Is this sort of along the lines that you were thinking?

Sure! In Twig they're called blocks, but same concept. ([more info](https://twig.symfony.com/doc/3.x/tags/embed.html))

**Comment by gerardo-rodriguez** [comment]
<img width="874" alt="Screen Shot 2021-06-08 at 1 54 04 PM" src="https://user-images.githubusercontent.com/459757/121256220-2dc1f180-c861-11eb-89d4-5501c940a908.png">

@tylersticka Now that we have a Default, Secondary, and Tertiary button style, I'm wondering how to handle the _pressed_ state from a design perspective for each of those buttons.

Referring to [the original screenshot in this GH issue](https://github.com/cloudfour/cloudfour.com-patterns/issues/1094#issue-767994616), it appears the Default button changes to the Secondary styled button when pressed.

Do we intend to keep that behavior? How do we handle the Secondary and Tertiary buttons?

When a toggle button:
- Default styles (not pressed) => Secondary styles? (pressed)
- Secondary styles (not pressed) => Secondary styles? (pressed)
- Tertiary styles (not pressed) => Tertiary styles? (pressed)

I wonder, instead, if it makes more sense to keep the button style the same for both the pressed and unpressed state. 

For example:
- Default styles (not pressed) => Default styles (pressed)
- Secondary styles (not pressed) => Secondary styles (pressed)
- Tertiary styles (not pressed) => Tertiary styles (pressed)

Thoughts? 🔍 👀 🤔

**Comment by tylersticka** [comment]
@gerardo-rodriguez I think your instinct is correct.

In [my article on button states](https://cloudfour.com/thinks/designing-button-states/#3-expanded-toggled-selected) and in design systems like [Material](https://material.io/components/buttons#toggle-button), [Royal Navy](https://docs.royalnavy.io/components/switch/) and [uStyle](https://ustyle.guide/pattern-library/forms.html#toggle), the pressed state is a variation of the unpressed state.

I suspect the switch from "primary" to "secondary" was based on the button classes we already had at the time.

**Comment by gerardo-rodriguez** [comment]
Closing this issue in favor of #1508. 

After further exploration, we realized we do not need a toggling pattern as it is not the best solution for this UX challenge. Instead, the intent will be to refactor the existing notifications subscription UI to be more accessible.
