### ISSUE TITLE
Author pattern(s) - development

### ISSUE THREAD

**Issue by AriannaChau** [cloudfour/cloudfour.com-patterns#1215]
Here are the new designs for the byline:

![byline-small](https://user-images.githubusercontent.com/24928337/117868001-e6d6e100-b24d-11eb-9430-7af5418effaa.jpg)
![byline-large](https://user-images.githubusercontent.com/24928337/117868012-ec342b80-b24d-11eb-820e-0d8e4932cf24.jpg)

The screenshots are examples of multiple authors. We've also decided for now to keep the extra information (technical reviews, illustrations) out of the byline.
 
Here is the design card for this task for more context: https://github.com/cloudfour/cloudfour.com-patterns/issues/1093

**Comment by tylersticka** [comment]
Just some considerations for development:

- If possible, this should leverage `o-media`, `o-bunch` and `c-avatar`
- I'm torn on the date being broken out of the main container at small sizes. I think it would simplify implementation a lot to keep things consistent, and I think the three-author use case that influenced that change is a lot less likely than one or two authors.
