### ISSUE TITLE
npm ci finishes but npm run storybook has issues when npm 7.x is used

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#1226]
I was dealing with some weird issues related to a feature I was developing, and I decided to try clearing the cache and installing `npm ci`. The version of `npm` I had installed was the latest (`7.13.0`); I had recently updated to make sure I wasn't replacing our v2 lockfile with a v1 lockfile.

The `npm ci` task would go through a series of `reify` commands, until the last one displayed would hang for a while. But then eventually it would stop hanging and say it had completed successfully. But when I tried running `npm run storybook`, it would complain about missing Node binaries and other "no such file or directory" errors relating to `node_modules`. This persisted even after running `npm cache verify`, `npm cache clean`, and manually deleting all of `node_modules`.

Finally, I used `nvm` to make sure my Node version was the latest `lts` version (`14.17.0`), which reset my local npm version to `6.14.13`. I tried running `npm ci` again, and this time it worked without any issues, as did `npm run storybook`.

Possible fixes I haven't tried:
- Updating npm with this updated version of Node. Maybe the issue was the Node version I was using and not npm?
- Running `npm i`. I just didn't want to replace our lockfile unnecessarily.
- Updating to a newer version of Node. Since this is _our_ project, it's really up to us if we want to be more aggressive than `lts` or not.

**Comment by calebeby** [comment]
I think this is fixed. I cannot reproduce this issue on the latest `v-next`.

But if I go back to commit 73615668b3c9b88dc1ec378eb6aca100396c302b, which was when this issue was opened, I _can_ reproduce it:

```
git checkout 73615668b3c9b88dc1ec378eb6aca100396c302b
npm ci && npm run storybook
```

I'll wait till @tylersticka confirms before closing

**Comment by tylersticka** [comment]
Thank you, @calebeby! I can confirm in the latest `v-next` with the latest `npm` this issue no longer occurs. 👍
