### ISSUE TITLE
Add comment thread pattern - dev.

### ISSUE THREAD

**Issue by AriannaChau** [cloudfour/cloudfour.com-patterns#1238]
We've added a prototype for the new comment thread designs, issue here: https://github.com/cloudfour/cloudfour.com-patterns/issues/487

They just now need to be turned into an actual pattern.

**Comment by tylersticka** [comment]
Remaining effort for this is represented by these issues...

- #1389 
- https://github.com/cloudfour/cloudfour.com-wp/issues/515
