### ISSUE TITLE
Email signup forms - Development

### ISSUE THREAD

**Issue by AriannaChau** [cloudfour/cloudfour.com-patterns#1260]
We can now turn this into an actual pattern. 

There should be some discussion regarding the Cloud Cover component and if it should have different breakpoints. Currently, we'd like the button and input to be on the same line a little sooner but the Cloud Cover component makes things a little squished. This applies to the email signup form that's located at the top of the page.

Here is the original issue: https://github.com/cloudfour/cloudfour.com-patterns/issues/1088
Here is the PR (with screenshots): https://github.com/cloudfour/cloudfour.com-patterns/pull/1259

**Comment by tylersticka** [comment]
Related: #1258 #1256

**Comment by tylersticka** [comment]
Closing this issue in favor of https://github.com/cloudfour/cloudfour.com-patterns/issues/1339
