### ISSUE TITLE
Refine source examples in individual stories

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#1289]
Our code previews to date were developed before we had anything close to useful source previews.

As of #1285, we not only have really nice automatic source previews, but we also have a new utility function we can use to generate previews more manually in cases where our demo source _must_ be disconnected somewhat from the actual theme code.

This issue represents going through our existing stories and making the necessary changes to improve the source previews where possible. Changes may include:

- Simplifying demos that may be replaced with the actual template and `args`
- Specifying the `Story` element's `source` or `templateSource` parameters using the aforementioned utility function
- When a story is particularly complex, unique or time-consuming, adding a TODO comment or creating a separate issue to refine at a later date

**Comment by gerardo-rodriguez** [comment]
Am I correct in understanding the source code previews can't handle `block` content? For example, the [Card component](https://v-next--cloudfour-patterns.netlify.app/?path=/docs/components-card--content-blocks) has multiple content blocks, is this an example of a component we leave alone for now?

**Comment by tylersticka** [comment]
I don't think there's any component we couldn't address in some fashion using one of the bullets in this issue's description. If all else fails, you can manually specify a string (`{% block 'content' %}...{% endblock %}`) representing the block.

**Comment by gerardo-rodriguez** [comment]
@tylersticka I created #1447 to break out the work left for the Objects. 

I will go ahead and call this card "done". 😉
