### ISSUE TITLE
Silence or resolve Babel warnings in Terminal

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#1291]
When running `npm run storybook`, there are zillions of occurrences of this warning:

```
Though the "loose" option was set to "false" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-property-in-object since the "loose" mode option was set to "true" for @babel/plugin-proposal-private-methods.
The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
        ["@babel/plugin-proposal-private-property-in-object", { "loose": true }]
to the "plugins" section of your Babel config.
```

I believe I looked into this once and it had something to do with a recent Storybook update, but I can't recall exactly.

**Comment by calebeby** [comment]
It looks like this is a problem from storybook and once they publish 6.3.0, it will be fixed: https://github.com/storybookjs/storybook/issues/14805#issuecomment-849600558

**Comment by spaceninja** [comment]
@tylersticka We're now running Storybook 6.3 and I don't see these errors anymore. Are you okay with me closing this issue?
