### ISSUE TITLE
Main JavaScript outputs are missing vendor scripts

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#1299]
In particular our Prism stuff seems to be missing from `cloudfour-patterns.js`.

It looks like those directories may simply be missing from our Rollup configuration?

https://github.com/cloudfour/cloudfour.com-patterns/blob/a1f7d76c64cc63d32bc4ee99777556d9cdea5ee7/gulpfile.js/tasks/build-scripts.js#L25

**Comment by calebeby** [comment]
@tylersticka If we combine the prism stuff with our main bundle, there is no longer an opportunity for tree-shaking or lazy loading, because the Prism imports modify globals and are not side-effect free. Can we generate a separate bundle for the prism stuff so that consumers of the pattern library don't have to load prism, or they can defer its loading?

**Comment by tylersticka** [comment]
@calebeby I think that's a great idea. We might also be able to intelligently load it on pages that actually need it and not on others.

**Comment by calebeby** [comment]
@tylersticka Actually now that I look at it, is the prism config necessarily something that will be same across all projects? It seems like the language support for cloudfour.com is probably different from what we need for storybook in this repo. Would it make sense to not have the prism config as a published part of the pattern library?

**Comment by tylersticka** [comment]
@calebeby If Storybook is using our Prism config at all beyond displaying it in stories, that's by accident. The language support is based on the languages we think Cloud Four would talk about and that we've tweaked our theme to support.

Can you explain in more detail what you're proposing (if anything)?

**Comment by calebeby** [comment]
@tylersticka what I am proposing is moving our prism config that we have in this repo to cloudfour.com-wp and then replacing the one here with only the language support we need for our storybook stories

**Comment by tylersticka** [comment]
@calebeby I'm open to that. I think they'll need to be the same since we need to be able to visualize our theme changes here in the same languages we use on the blog.

**Comment by calebeby** [comment]
@tylersticka can we close this then? I think https://github.com/cloudfour/cloudfour.com-wp/issues/529 represents the rest of the work for this (I can add a comment there)

**Comment by tylersticka** [comment]
@calebeby I'd like to keep that open because it's still not clear to me if manually adding a class to the block is an ideal solution, but it's hard to get a feel for that until this is resolved here.

**Comment by calebeby** [comment]
@tylersticka I meant close _this_ issue, and leave https://github.com/cloudfour/cloudfour.com-wp/issues/529 open.

I think _this_ issue is ready to be closed because it sounds like we decided we don't need to include the prism stuff in the npm package

**Comment by tylersticka** [comment]
Got it, I misunderstood! Go for it
