### ISSUE TITLE
Featured row pattern

### ISSUE THREAD

**Issue by dromo77** [cloudfour/cloudfour.com-patterns#1375]
We added a new prototype of the [article listing page](https://v-next--cloudfour-patterns.netlify.app/?path=/story/prototypes-article-listing--example). In it there are featured articles. We'll need a pattern that lays out the content in these sections. It should include: 

- title/introductory content
- the main content
- optional link to additional content

**Large Screens**
![Screen Shot 2021-07-08 at 11 36 25 AM](https://user-images.githubusercontent.com/42841342/125140199-d49ae700-e0c6-11eb-9624-e005449b1149.png)

**Small Screens**
![Screen Shot 2021-07-09 at 11 48 04 AM](https://user-images.githubusercontent.com/42841342/125140225-ea101100-e0c6-11eb-9a97-8a0ab20bebaf.png)

**Comment by AriannaChau** [comment]
Just wanted to comment and show this also applies on the case study listings page so best use cases can be taken into account here!

<img width="1440" alt="Screen Shot 2021-07-12 at 9 20 14 AM" src="https://user-images.githubusercontent.com/24928337/125326583-0e523480-e2f7-11eb-880d-2629c828e649.png">

In this particular prototype, the title and the content have the same font baseline
<img width="593" alt="Screen Shot 2021-07-12 at 9 59 22 AM" src="https://user-images.githubusercontent.com/24928337/125327867-7c4b2b80-e2f8-11eb-80ad-54a4f7f255c4.png">
