### ISSUE TITLE
Heading font weight modifier

### ISSUE THREAD

**Issue by dromo77** [cloudfour/cloudfour.com-patterns#1377]
By default, headings have a bold font weight `700`. In the new [article listing prototype](https://v-next--cloudfour-patterns.netlify.app/?path=/story/prototypes-article-listing--example), some of the headings have a lighter font weight `300`. We need a modifier or some way to adjust the font weight for headings.

**Default Font Weight**
![Screen Shot 2021-07-09 at 3 17 30 PM](https://user-images.githubusercontent.com/42841342/125141054-ccdc4200-e0c8-11eb-9e55-f47e215c8be5.png)

**Light Font Weight**
![Screen Shot 2021-07-08 at 11 36 25 AM](https://user-images.githubusercontent.com/42841342/125141093-e1b8d580-e0c8-11eb-8131-ed49e5380fc7.png)

**Comment by AriannaChau** [comment]
This is also present in the [case study page](https://v-next--cloudfour-patterns.netlify.app/iframe.html?id=prototypes-case-study-listings--example&args=&viewMode=story).
<img width="1440" alt="Screen Shot 2021-07-12 at 10 33 15 AM" src="https://user-images.githubusercontent.com/24928337/125331240-92f38180-e2fc-11eb-9f9f-d7e0aa12bb54.png">
