### ISSUE TITLE
Comment form reply behavior

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#1389]
Our Comment component contains a placeholder for replies, but it does not yet integrate our Comment Form.

The experience should behave similarly to how it does on the live site:

![reply-behavior](https://user-images.githubusercontent.com/69633/125327673-368e6300-e2f8-11eb-8a26-363653661b95.gif)

Note the focus of the first field and the reply form popping up at the top rather than scrolling below the other replies.

**Comment by Paul-Hebert** [comment]
@tylersticka I started working on adding in the reply form. It's feeling a little bulky to my eye. I wonder if it would be helpful to give this a design pass focusing on:

1. Making the form more compact when displayed inline after a comment
2. Differentiating the reply form from the comment you're replying to

What do you think? Would it be helpful for me to do some explorations before I get too far on this?

<img width="1700" alt="Screen Shot 2021-07-16 at 4 31 57 PM" src="https://user-images.githubusercontent.com/5798536/126017748-f03b096e-1577-446d-a407-efc35a7992f9.png">

**Comment by tylersticka** [comment]
> It's feeling a little bulky to my eye.

This feels a little exaggerated to me in your screenshot since the component isn't constrained width-wise. In practice, we'll be displaying the comment thread inside of [a prose-width container object](https://v-next--cloudfour-patterns.netlify.app/?path=/story/objects-container--prose).

> Making the form more compact when displayed inline after a comment

I'm open to ideas. I think it will simplify things technically if the form is consistent between replies and new comments, so any ideas would ideally translate well between both.

> Differentiating the reply form from the comment you're replying to

Very open to this! At the very least we should probably transform the containing comment into [the `--thread` variety](https://v-next--cloudfour-patterns.netlify.app/?path=/story/components-comment--with-reply-thread).

**Comment by Paul-Hebert** [comment]
That makes sense. I'll try using the `--thread` modifier and sticking the whole thing in a Prose container. I'll see how that looks and whether it still feels bulky or not :+1:

**Comment by tylersticka** [comment]
> That makes sense. I'll try using the `--thread` modifier and sticking the whole thing in a Prose container. I'll see how that looks and whether it still feels bulky or not 👍

And if `--thread` is something we end up needing to toggle on and off with JavaScript, it might actually be better suited for an `is-threaded` state class rather than a modifier! That may have been short-sighted of me

**Comment by Paul-Hebert** [comment]
That makes sense :+1:
