### ISSUE TITLE
Column content alignment pattern

### ISSUE THREAD

**Issue by AriannaChau** [cloudfour/cloudfour.com-patterns#1390]
For the [case study listings page](https://v-next--cloudfour-patterns.netlify.app/iframe.html?id=prototypes-case-study-listings--example&args=&viewMode=story), there are some columns that are in different sections but are still aligned vertically, particularly the book is aligned with the icons below, and the text for each one is also aligned. I'm not exactly sure what the solution for this would be...feel free to reach out if you need more info.

<img width="635" alt="Screen Shot 2021-07-12 at 10 19 05 AM" src="https://user-images.githubusercontent.com/24928337/125329638-9980f980-e2fa-11eb-9ce9-25a487dd820e.png">

**Comment by tylersticka** [comment]
For added context, the alignment was mainly to make sure the content aligns nicely with headings in the pattern now known as a Feature Group. Anyone taking this on should familiarize themselves with that layout object as well as the case study listings prototype.

**Comment by tylersticka** [comment]
I'm having a hard time figuring out how this would actually work as a pattern. I thought I'd comment to make it clear that I'm open to solutions that involve some design compromises in the short-term.
