### ISSUE TITLE
Prototype speaking pages

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#1417]
Our site's "speaking" section consists of two templates:

- One summarizing upcoming events (if any): https://cloudfour.com/presents/
  - Prototype with upcoming events visible: https://cloudfour-patterns.netlify.app/pages/talk-core.html
- One for individual events: https://cloudfour.com/presents/designing-progressive-web-apps/

In theory, we should have ~all~ most of the patterns necessary to pull off these templates:

- `o-container`: Ability to constrain the article or page to width with fluid padding
- `c-heading`: Ability to size headings above the default `h1` for the article/page title (see also: #1416)
- `c-author`: For showing who presented the topic
- `o-rhythm`: For spacing apart page content
- `c-card` and `o-deck`: For displaying individual talks
- `c-calendar-date` and `o-media`: For upcoming events
- `c-comment` and `c-comment-form`: For article discussions
- `o-embed` for talk media (videos, slides, etc.)

What we don't have is a pair of prototypes representing the complete combination. Some questions to answer along the way:

- Does the container have adequate padding (both vertically and horizontally)?
- For single talk pages, what size should the heading be when it is not inside of a Cloud Cover?
- Is our rhythm object's generous spacing enough between page sections?
- What patterns (if any) are still missing? Which need improvements?

You may also make smaller tweaks along the way to improve the polish of this page's design!

**Comment by dromo77** [comment]
The outcome of this card should be two prototypes:

1. A listing page that shows upcoming and past talks
2. Individual event page

Leaving a note that one of the prototypes, the [listing page](https://v-next--cloudfour-patterns.netlify.app/?path=/story/prototypes-speaking-listing--example), has been approved.
