### ISSUE TITLE
Token documentation no longer works

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#1420]
It appears that Storybook was updated to 6.3. With this change, the docs pages located at Design ▸ Tokens no longer display anything but a blank page.

**Comment by calebeby** [comment]
Oops, my fault for not noticing that

**Comment by calebeby** [comment]
@tylersticka this is a storybook bug:

- https://github.com/storybookjs/storybook/issues/15282
- https://github.com/storybookjs/storybook/issues/15359

There is a PR: https://github.com/storybookjs/storybook/pull/15492

We could:

- Let it be broken until they fix it and release it
- Change all of the \<code> blocks in .mdx files that have non-string children to cast them to string first:
  ```diff
  - <code>aspect-ratio.${_.kebabCase(attributes.item)}</code>
  + <code>{`aspect-ratio.$${_.kebabCase(attributes.item)}`}</code>
  ```

**Comment by tylersticka** [comment]
Can you work with @gerardo-rodriguez and/or @Paul-Hebert to determine the best course of action?

**Comment by calebeby** [comment]
It seems like storybook makes releases pretty often. That PR that fixes it has recent activity and it seems like it could probably be merged soon. Is it ok if we leave the tokens pages broken for a couple weeks or so, or do we need it to be working until then?

**Comment by gerardo-rodriguez** [comment]
I'm okay leaving it broken for a bit (a couple of weeks or so) assuming we don't need it up before then. If the priority is higher than my current read, then I'd be okay changing the code blocks in the `.mdx` files.

**Comment by Paul-Hebert** [comment]
Another option could be downgrading to the version before this broke and then waiting to upgrade until they merge that PR? Would that break other stuff?

**Comment by calebeby** [comment]
Yeah I think we could downgrade safely AFAIK

**Comment by Paul-Hebert** [comment]
Cool, if this is a high priority I'd push for that. If waiting a couple weeks isn't a big deal I'm also fine with that.

**Comment by tylersticka** [comment]
@calebeby If we're waiting on the fix, can we label this as `blocked` and move it to the backlog?

**Comment by tylersticka** [comment]
This appears to have been resolved by a Storybook upgrade.

**Comment by tylersticka** [comment]
Sorry, closing this was premature. Some token pages seem to be working, others are not.

**Comment by calebeby** [comment]
@tylersticka I think this was fixed by a storybook update, it seems to be working now. Could you double-check that?

**Comment by tylersticka** [comment]
@calebeby Confirmed! 🎉 

Thanks for following up!
