### ISSUE TITLE
Plan/Implement Comment Form submission

### ISSUE THREAD

**Issue by Paul-Hebert** [cloudfour/cloudfour.com-patterns#1428]
We have a Comment Form pattern which will be used in a couple places on the Wordpress site (leaving a comment and replying to a comment. Check out the Comment pattern for an example of the latter.)

Right now the form has no logic around validation or submission. We should investigate how this will be integrated into Wordpress and what needs to happen on the pattern side. My guess is we'll want validation to happen in the patterns, and we'll want a way for Wordpress to define what happens on submission.

This card could include implementation, or could lead to creating new cards based on research conclusions.

**Comment by calebeby** [comment]
@Paul-Hebert What kind of validation are you thinking of? Is just a non-empty check enough? Or do we also want to scan the text for non-allowed html tags to warn that they won't be accepted? Or anything else?

**Comment by calebeby** [comment]
> What kind of validation are you thinking of? Is just a non-empty check for most of the fields + valid email enough? Or do we also want to scan the text for non-allowed html tags to warn that they won't be accepted? Or anything else?

Also, do we want any custom messaging for validation warnings or are we fine with the browser messaging?

<img width="594" alt="Screen Shot 2021-08-17 at 12 45 04 PM" src="https://user-images.githubusercontent.com/13206945/129795040-d572a534-859f-4b26-88f9-13e6aae3428a.png">

I think if we have custom validation, other than what the browser is able to validate based on attributes, we'd need custom warnings too.

cc @tylersticka

**Comment by tylersticka** [comment]
> Is just a non-empty check for most of the fields + valid email enough?

I think this is probably enough.

**Comment by tylersticka** [comment]
> Also, do we want any custom messaging for validation warnings or are we fine with the browser messaging?

Browser messaging is fine, I think.
