### ISSUE TITLE
Refine source examples in individual stories for Objects

### ISSUE THREAD

**Issue by gerardo-rodriguez** [cloudfour/cloudfour.com-patterns#1447]
This card is "part 2" of #1289. 

All of the Components' stories were updated but now the Objects need to be updated as well.

**Comment by tylersticka** [comment]
- [ ] Bunch
- [ ] Button Group
- [ ] Container
- [ ] Deck
- [ ] Embed
- [ ] Feature Group
- [ ] Form Group
- [ ] Input Group
- [ ] Media
- [ ] Overview
- [ ] Page
- [ ] Rhythm

**Comment by tylersticka** [comment]
![That's all, folks!](https://media.giphy.com/media/xUPOqo6E1XvWXwlCyQ/giphy.gif)
