### ISSUE TITLE
Speaker pattern

### ISSUE THREAD

**Issue by dromo77** [cloudfour/cloudfour.com-patterns#1463]
On the [speaking event prototype](https://v-next--cloudfour-patterns.netlify.app/?path=/story/prototypes-speaking-event--example), there is a pattern similar to `Author`. It includes the speaker name and title. The `Author` pattern only supports a name and date field. We could update `Author` to include an optional text field for titles or we could add a new component.

![Screen Shot 2021-08-02 at 4 11 56 PM](https://user-images.githubusercontent.com/42841342/127934705-acd5a997-5df8-4e49-a68e-980617b4c810.png)

**Comment by gerardo-rodriguez** [comment]
Thanks, @dromo77! 

I like the idea of reusing the `Author` component if we can. (Though I'm not opposed to creating a new one if we find it makes more sense)

I'm curious about your thoughts on how to handle presentations that have multiple speakers? Unless I'm mistaken, Jason and I will be presenting the first Cloud Four co-presented talk for PWA Summit this year. That means we actually have a use case to design for. 🙂 

Here is what co-authors looks like, for reference:
<img width="438" alt="Screen Shot 2021-08-20 at 2 43 10 PM" src="https://user-images.githubusercontent.com/459757/130296377-1ebfeb1d-1262-4ed7-95f7-73b51732f6b6.png">

I was trying to imagine what it might look like when there are two titles to account for if a presentation/even is co-presented. 

Wanted to share with you before I got too far to make sure I didn't pin ourselves into a corner. I'll think about it a bit more as well. 😉

**Comment by dromo77** [comment]
That's a great question @gerardo-rodriguez! I didn't consider multiple speakers when I created the prototype. There isn't an immediate solution that comes to mind. It seems like we should account for that use case in the design before we start updating or building a new component. I'm wondering if we should create a card for the design work and mark this as blocked until it's complete?

**Comment by gerardo-rodriguez** [comment]
> There isn't an immediate solution that comes to mind.

Yeah, nothing obvious comes to me either. 😅 

> I'm wondering if we should create a card for the design work and mark this as blocked until it's complete?

Good idea! Would you like to create a card or would you prefer I do so?

Thanks, @dromo77! 🙂

**Comment by dromo77** [comment]
@gerardo-rodriguez  Just created an issue https://github.com/cloudfour/cloudfour.com-patterns/issues/1493. Going to mark this as blocked until that's done.

**Comment by dromo77** [comment]
Removing the blocked label, there's a [prototype](https://v-next--cloudfour-patterns.netlify.app/?path=/story/prototypes-speaking-event--multiple-speakers) of the speaking event page that includes multiple speakers. We landed on including the title for single speakers and dropping the titles when there are multiple speakers.

Single Speaker
<img width="247" alt="Screen Shot 2021-10-05 at 2 44 56 PM" src="https://user-images.githubusercontent.com/42841342/136107134-3e0747ca-4e5e-44f8-aab1-41dd533686ae.png">

Multiple Speakers
<img width="454" alt="Screen Shot 2021-10-05 at 10 15 08 AM" src="https://user-images.githubusercontent.com/42841342/136107163-fa49e745-0ac7-4a89-a565-df67be785607.png">

**Comment by tylersticka** [comment]
@gerardo-rodriguez Is the assignment on this issue correct? (It looks like you self-assigned back in August.)

**Comment by gerardo-rodriguez** [comment]
@tylersticka Oops, sorry, I never unassigned myself. 😬
