### ISSUE TITLE
Add footnote-related patterns

### ISSUE THREAD

**Issue by AriannaChau** [cloudfour/cloudfour.com-patterns#1479]
While prototyping for the single article page, I noticed some footnotes that we don't have an existing pattern for:

<img width="793" alt="Screen Shot 2021-08-11 at 11 13 39 AM" src="https://user-images.githubusercontent.com/24928337/129081550-fda36dd2-c49f-4a4b-b74e-f01122e5cbfd.png">

<img width="757" alt="Screen Shot 2021-08-11 at 11 13 46 AM" src="https://user-images.githubusercontent.com/24928337/129081558-0c034487-fac2-4830-85b0-37f13c2fdf0c.png">

As far as how the pattern looks, I think it's fine. I think the arrows are a little large but I'm not losing any sleep over it. I wanted to create an issue to make sure we add these, but I will defer to @tylersticka as far as the current design to see if we need to make any tweaks going into the new library.

**Comment by tylersticka** [comment]
I agree that this should be an evolution using our latest patterns and tokens, not a revolution.

(The arrow may look a little better now that its stroke weight and dimensions have been slightly altered.)

**Comment by tylersticka** [comment]
I'm going to add the `dev` label to this as well. Although there are some design considerations, I don't know that this needs a separate prototyping phase since we don't plan on straying very far from the existing design.
