### ISSUE TITLE
Sky Nav logo feels too large on small screens

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#1514]
On large screens, the Sky Nav logo feels nicely balanced (IMO):

<img width="1700" alt="Screen Shot 2021-08-30 at 9 40 15 AM" src="https://user-images.githubusercontent.com/69633/131373916-14818817-5bf1-49b1-b7c3-5f088b406ea1.png">

But on smaller screens, it feels a bit confined:

<img width="358" alt="Screen Shot 2021-08-30 at 9 41 02 AM" src="https://user-images.githubusercontent.com/69633/131374004-164f5573-0606-435d-b364-b8ba378f86c6.png">

Ideally it'd be a bit more balanced with the size of the button (this is just a quick mockup):

<img width="358" alt="Screen Shot 2021-08-30 at 9 41 02 AM adjusted" src="https://user-images.githubusercontent.com/69633/131374198-ef4bdb4b-8560-4bd0-b1d6-ed9fe4b86666.png">

This issue is labeled `design` because it involves design thinking but `dev` because I believe the adjustment can be made directly to the Sky Nav component without a separate prototyping step.

**Comment by calebeby** [comment]
Oops forgot to close this 🤦
