### ISSUE TITLE
Style <hr>s

### ISSUE THREAD

**Issue by Paul-Hebert** [cloudfour/cloudfour.com-patterns#1520]
Right now our `<hr>` elements are using default styles:

![image](https://user-images.githubusercontent.com/5798536/132068118-16e5fb8c-9de7-4efc-b9aa-67824de77c4d.png)

We should make these fit our brand better and use our brand colors. I recently styled a divider for Footnote patterns which might be a useful starting point for colors/thickness (though I'm open to other ideas!)

![image](https://user-images.githubusercontent.com/5798536/132068164-095a3df4-4c2f-4eef-a300-ac1ebbc45635.png)

**Comment by Paul-Hebert** [comment]
@tylersticka it seems like could just style `hr` directly? Is there any reason that's a bad idea and this should be constrained to a CMS Content class or something like that?

**Comment by tylersticka** [comment]
@Paul-Hebert Styling directly sounds fine!

**Comment by Paul-Hebert** [comment]
It looks like we did take a pass at styling the Gutenberg divider: https://v-next--cloudfour-patterns.netlify.app/?path=/story/vendor-wordpress-core-blocks--separator

@tylersticka should we standardize around this design? Or give it another pass (and apply those styles to the Gutenberg block)?

**Comment by tylersticka** [comment]
@Paul-Hebert I think it could use another pass.
