### ISSUE TITLE
Ensure elements in Gutenberg markdown blocks match their block equivalents

### ISSUE THREAD

**Issue by Paul-Hebert** [cloudfour/cloudfour.com-patterns#1522]
We've added custom styles for a number of Gutenberg blocks: https://v-next--cloudfour-patterns.netlify.app/?path=/docs/vendor-wordpress-core-blocks--separator#wordpress-core-blocks

Some of the elements these blocks generate can also be generated using the markdown block (like `table`s, `hr`s, `blockquote`s, code blocks, etc.)

We should ensure that when these elements are created in a markdown block we're applying the same styles to them. The markdown block has a `.wp-block-jetpack-markdown` class we can hook into like so:

```css
.wp-block-jetpack-markdown blockquote{ }
```

**Comment by Paul-Hebert** [comment]
We should also ensure that these styles are applied to "legacy" blog posts when appropriate (blog posts written for the old theme, not using Gutenberg.)

For example, whatever styles we apply to our block quotes should apply to block quotes in those old posts. It's not clear if _all_ of the styles applied to markdown blocks should apply to legacy posts or only a subset. We may want to create a `cms-content` class or something along those lines to apply those styles to legacy posts as well as markdown blocks. 

@see https://github.com/cloudfour/cloudfour.com-wp/pull/607

**Comment by tylersticka** [comment]
FYI, @spaceninja is a good resource for techniques based on a recent client project.

**Comment by calebeby** [comment]
@spaceninja can I assign you to this one? I think you will be much better than me at this since I am not very familiar with gutenberg
