### ISSUE TITLE
Add ability for search input's icon to use an increased font size

### ISSUE THREAD

**Issue by Paul-Hebert** [cloudfour/cloudfour.com-patterns#1540]
The [article listing prototype](https://v-next--cloudfour-patterns.netlify.app/?path=/story/prototypes-article-listing--example) includes a search form with an icon button. That icon has `1.25em` font size. I can't figure out how to do this with the existing components. I tried using the `c-button__extra` class on my button content but that also affected margins. 

Should we make a test utility? A button/icon modifier? Something else? Am I missing an existing feature that handles this?

<img width="1448" alt="Screen Shot 2021-09-13 at 12 38 23 PM" src="https://user-images.githubusercontent.com/5798536/133146052-9681ee3c-7181-44df-a1ae-b0f6937c08a8.png">

**Comment by tylersticka** [comment]
Our buttons have support for `content_icon_start` and `content_icon_end`. These are sized a bit differently from the default as well. For consistency, I wonder if we need to add support for just a plain ol' `content_icon` and accessible text?

/cc @gerardo-rodriguez (who implemented the other `content_icon` features)

**Comment by Paul-Hebert** [comment]
Yeah, that makes sense to me :+1:

**Comment by tylersticka** [comment]
I'm noticing a few other, small issues with the current icon implementation. I've increased the size a bit to account for handling those things, which will make addressing the root issue a lot more straightforward (I think).
