### ISSUE TITLE
Prototype 404 and offline pages

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#1546]
Our live site has a 404 page with a shrugging robot and an old Ignite talk that Jason gave as a bit of an easter egg: https://cloudfour.com/foo

We also have a page that displays if the user is offline and tries to navigate somewhere that wasn't downloaded beforehand. It includes a subtle animation of a wi-fi symbol gradually going "off." This can be accessed directly here: https://cloudfour.com/offline/

We should do a pass of these two experiences to make sure they're in line with the updated site design.

(This may be split into two separate issues, I just wanted to make sure these were considered together for overall consistency. Also fine for two designers to get assigned to the same issue!)

**Comment by Paul-Hebert** [comment]
I wonder if some of this content could also be useful for #1543 and #1544 ?
