### ISSUE TITLE
Offline variation of alert pattern

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#1547]
Our live site includes an alert when the user has gone offline. We do this so it won't be a surprise if they attempt to interact with something that still requires connectivity, such as a contact form or an embedded element (video, CodePen, etc.)

![Screen Shot 2021-09-16 at 08 49 06](https://user-images.githubusercontent.com/69633/133644256-5adf1178-7322-4b1c-9d5a-1220e780f584.png)

An updated Alert pattern was designed, but we had some difficulty landing on an accessible "offline" variation. You can see the default variation here: https://v-next--cloudfour-patterns.netlify.app/?path=/docs/components-alert--full-width#alert

This task involves designing a modifier class that will style the alert well for notifying the user they are offline. It should be prominent but not alarming (since the user didn't do anything wrong), and it should look nice against the blue of our Cloud Cover pattern. And unlike the current offline bar, it should pass our accessibility guidelines.

It's also okay to explore additions for this scenario, such as an icon, but that's not strictly necessary.

**Comment by AriannaChau** [comment]
I'm assigning myself to this because I'm interested in designing it. It's not my next task and if I dev wants to also assign themselves and we could possibly go back and forth, please feel free!

**Comment by tylersticka** [comment]
Updated assignment so @dromo77 can pick up where Arianna left off. 🙂
