### ISSUE TITLE
Theme Pages are Broken

### ISSUE THREAD

**Issue by spaceninja** [cloudfour/cloudfour.com-patterns#1585]
<img width="1708" alt="Screen Shot 2021-11-15 at 10 58 22 AM" src="https://user-images.githubusercontent.com/257309/141838670-157c286c-d808-47cd-a3f8-5371af9e2e43.png">

**Comment by tylersticka** [comment]
This one's my fault: I removed these templates in #1569 and did not remember we were including them in other examples.
