### ISSUE TITLE
Large amount of white space below Overview blocks in Safari

### ISSUE THREAD

**Issue by spaceninja** [cloudfour/cloudfour.com-patterns#1596]
There's a large amount of whitespace visible in Safari below Overview blocks. This is visible on the Overview page and the Article Listing prototype.

<img width="1707" alt="Screen Shot 2021-11-23 at 4 40 06 PM" src="https://user-images.githubusercontent.com/257309/143150913-b9f044ee-0d05-4d26-9c5b-2f00ace5f86c.png">

**Comment by tylersticka** [comment]
This is a super bizarre bug. It does not occur when the Overview content does not include a CSS column list, but it also does not occur with the CSS column list outside of that context. What's _most_ bizarre, though, is that the height doesn't seem to be part of those elements at all... it seems to be impacting the total outer page height. In this example, "Hello world" is appended to the root HTML, completely outside the scope of Overview or List patterns:

<img width="656" alt="Screen Shot 2021-12-07 at 10 44 33 AM" src="https://user-images.githubusercontent.com/69633/145087948-d01a157f-97ae-4d15-85a3-bee22710755c.png">

I thought it first it might be Storybook, but even when I view the pattern in its own window in isolation, the expanded page height remains. It also remains if I un-check all styles on the `body` and `:root`/`html` and set the content container to `overflow: hidden`. Even the browser thinks that `html` ends where it's supposed to:

<img width="1625" alt="Screen Shot 2021-12-07 at 10 49 04 AM" src="https://user-images.githubusercontent.com/69633/145088499-89d5b68d-5cd3-4d71-8d8e-eb4a4605c9c1.png">

So now I guess I'll just try various CSS things. I already tried specifying grid rows, to no avail, and also adding `overflow: hidden`. There are other CSS column bugs specific to Safari I'm witnessing, so maybe I'll try resolving some of those to see if that helps. What a mess.

**Comment by tylersticka** [comment]
Okay, I now think this has something to do with the CSS columns and the Dot Leader pattern. Because I removed everything but the column list and it still occurred, but when I removed the dot leader the problem went away.

Investigating...

**Comment by tylersticka** [comment]
I think I've narrowed it down. For some reason, when the `u-hidden-visually` utility is used within `c-dot-leader` which is housed within an `o-list` with columns, it's as if the extra height of those hidden elements is appended to the window's scroll height. 🤯

**Comment by tylersticka** [comment]
Okay, I think giving Dot Leaders a `position` of `relative` might resolve the issue. Alternatively adding a position property to the utility would work, but I'm nervous about unintentionally adding side effects.
