### ISSUE TITLE
Hovering a card with a cover image causes rounded corners to temporarily flicker in Safari

### ISSUE THREAD

**Issue by spaceninja** [cloudfour/cloudfour.com-patterns#1597]
In Safari, when you mouse over an avatar on the Team List page, it flickers for a second revealing the square shape of the avatar.

![Untitled](https://user-images.githubusercontent.com/257309/143151027-8602d064-bcd0-4f53-94ea-ad831e33a05e.gif)

**Comment by tylersticka** [comment]
Updated title as this isn't specific to circular cards or the team page.

**Comment by tylersticka** [comment]
Apparently a known issue since 2011 (!!!) 🤦 

https://bugs.webkit.org/show_bug.cgi?id=68196
