### ISSUE TITLE
Add supporting materials to Speaking Event page

### ISSUE THREAD

**Issue by dromo77** [cloudfour/cloudfour.com-patterns#1694]
The speaking event [prototype](https://v-next--cloudfour-patterns.netlify.app/iframe.html?id=prototypes-speaking-event--single-speaker) is missing an area for supporting materials. We should consider where the materials go and what they look like.

![Screen Shot 2022-03-29 at 11 20 11 AM](https://user-images.githubusercontent.com/42841342/160678927-ee4f8cfd-314f-4909-ad74-ab711a71579e.png)

**Comment by gerardo-rodriguez** [comment]
A couple of talks that have supporting material:
- https://cloudfour.com/presents/responsive-images-are-here-now-what/
- https://cloudfour.com/presents/svg-so-very-good/
