### ISSUE TITLE
Restrict automatic Storybook updates

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#1717]
A larger than average number of uncaught regressions seem to be due to Storybook updates that include breaking changes due to "experimental" features that don't conform to semantic versioning. Because the resulting errors only impact front-end documentation, often in subtle ways, they aren't caught by our current checks and they may even elude our reviewers. Because of this, it would be nice to put up more guard rails for automatic Storybook updates than for our other project dependencies.

---

/CC @calebeby @spaceninja

**Comment by calebeby** [comment]
Oops, sorry I missed this earlier. Yeah I can remove the auto-approve for storybook.
