### ISSUE TITLE
Author bio meta content should be within a prose container

### ISSUE THREAD

**Issue by gerardo-rodriguez** [cloudfour/cloudfour.com-patterns#1749]
Oops...

<img width="954" alt="Screen Shot 2022-04-25 at 3 59 47 PM" src="https://user-images.githubusercontent.com/459757/165188251-b579eefe-c431-4b62-a802-7049792c290c.png">

**Comment by gerardo-rodriguez** [comment]
@tylersticka This card may or may not be needed depending on the outcome of this:
> [I have an idea for how to improve this layout even more, but I think it constitutes a design change.](https://github.com/cloudfour/cloudfour.com-patterns/pull/1747#pullrequestreview-952489362 )

**Comment by tylersticka** [comment]
It seems necessary! I don't foresee that design change happening until post-launch.

Alternatively you could use CSS grid columns with a maximum width of our prose width design token.

**Comment by gerardo-rodriguez** [comment]
Thanks, @tylersticka, good idea!
