### ISSUE TITLE
Can the Subscribe submit UX be better?

### ISSUE THREAD

**Issue by gerardo-rodriguez** [cloudfour/cloudfour.com-patterns#1768]
After submitting the MailChimp form to subscribe to get weekly digests, the UX is a bit odd:

1. User enters their email into the input
2. User submits form
3. A new MailChimp page opens confirming subscription
4. User closes new MailChimp page
5. User sees subscription form again, with their email still in the input field
    - Should the input be cleared?
    - Show some sort of "success" message?
    - How do we know if the MailChimp form subscription was successful or not? Is this even possible?

![subscribe-email](https://user-images.githubusercontent.com/459757/166336994-7f59bb53-6686-42d2-b659-b0464172414c.gif)

**Comment by gerardo-rodriguez** [comment]
@tylersticka I assume this is a lower priority and not a launch blocker, but I'll defer to you. 😉

**Comment by tylersticka** [comment]
@gerardo-rodriguez It's the same experience as the live site, so definitely not a launch blocker.

Also going to close as I'm not sure if it's pattern- or experience-specific, or even if we're going to stay with that email service.
