### ISSUE TITLE
Stylelint flags valid CSS `min` and `max` functions as errors

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#1890]
In #1889 I used a CSS `max` function. Here's a simplified example:

```scss
.alignwide {
  margin-inline: max(-50vw + 50%, -16em);
}
```

This triggered the `scss/no-global-function-names` rule, which thought I was attempting to use Sass's `math.max` function.

This appears to have been fixed in `stylelint-scss` `4.0.1` and later: https://github.com/stylelint-scss/stylelint-scss/blob/master/CHANGELOG.md#401

Though I can't tell if that's a dependency of this project or [our stylelint config](https://github.com/cloudfour/stylelint-config-cloudfour) (or neither?).

**Comment by spaceninja** [comment]
Just did a bit of digging — `stylelint-scss` is included in our config via `stylelint-config-standard-scss`, which adds the ability for Stylelint to handle SCSS files, as well as four Stylelint configs — `stylelint-recommended`, `stylelint-standard`, `stylelint-recommended-scss`, and `stylelint-standard-scss`. (Just to make this more fun, many of those configs are overruled by SUIT's Stylelint config, which we're also loading. It's complicated, but trust me, it's worth it).

In this case, `stylelint-config-recommended-scss` has `stylelint-scss@^4.0.0` as a dependency, which is being set to `4.0.0` in our stylelint config's lockfile.

We could fix this a couple ways:

1. Manually updating our lockfile to specify `4.0.1` or later
2. Manually installing `stylelint-scss@4.0.0` as a depedency in our stylelint config (seems like overkill)
3. Ignoring this bug until Stylelint bumps the version in their recommended config.

I think option 1 makes the most sense. @calebeby any reasons you can think of not to do so?

**Comment by calebeby** [comment]
I would lean towards option 2, since `rm -rf package-lock.json node_modules && npm i` is a semi-frequent way that we might fix a dependency tree in the future, and that would discard that change. If our project needs a specific version of a package, it should be listed in `package.json`.

**Comment by spaceninja** [comment]
That makes sense, thanks @calebeby
