### ISSUE TITLE
Improve appearance of input focus state while in an input group

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#1944]
Because our focus states only happen on inputs themselves, when focusing an input in an input group it looks kinda broken:

<img width="635" alt="Screen Shot 2022-07-13 at 12 48 08 PM" src="https://user-images.githubusercontent.com/66242/178820124-8c785f75-81b6-4745-bc74-f547e5f300be.png">
<img width="408" alt="Screen Shot 2022-07-13 at 12 48 15 PM" src="https://user-images.githubusercontent.com/66242/178820131-332b25cd-febd-4bd2-bb26-b569af8f4fbb.png">

---

Thanks @megnotarte

**Comment by calebeby** [comment]
@tylersticka what does "fixed" look like for this?

- The border on the right side covers the line between the button and the text input
- The border goes the whole way around the combination input/button (I don't prefer this because it might be ambiguous whether the button is focused)
- Something else?

**Comment by tylersticka** [comment]
My first choice would be for the entire group to be selected. I don't find this ambiguous because if you hit return/enter from the input, it will submit the form. You can see an example for a public client project here: https://cpe-patterns.netlify.app/patterns/elements/forms.html#input-group

Here is a quick mockup:

<img width="740" alt="Screen Shot 2022-07-14 at 10 05 21 AM" src="https://user-images.githubusercontent.com/69633/179041465-52959836-18b7-4173-898d-6b101a26924d.png">

My second choice would be for the input to remain selected but the focus outline to not be cut off by the button:

<img width="720" alt="Screen Shot 2022-07-14 at 10 06 00 AM" src="https://user-images.githubusercontent.com/69633/179041847-4a9bd5fd-d9b6-4864-949e-dd98d62c49db.png">
