### ISSUE TITLE
Upgrade to WebPack 5

### ISSUE THREAD

**Issue by spaceninja** [cloudfour/cloudfour.com-patterns#1953]
Storybook now supports WebPack 5 with a bit of extra configuration: https://storybook.js.org/docs/react/builders/webpack#webpack-5

We have [numerous dependencies we can't update](https://github.com/cloudfour/cloudfour.com-patterns/issues/943) because they depend on WebPack 5, so this would be a good upgrade for us.

**Comment by spaceninja** [comment]
@calebeby I don't know your availability or how this would prioritize compared to other tasks, but if you had some bandwidth, this would be great to get your eyes on.

**Comment by calebeby** [comment]
@spaceninja I would guess this is closer to a 5-10 than a 2. I would rather switch to vite if that storybook integration is more stable/complete than it was last time we checked.

**Comment by calebeby** [comment]
Let's hold off until after launch regardless?

**Comment by calebeby** [comment]
I'm gonna investigate vite again, see if the ecosystem is more ready than last time we checked. If not, I'll look into webpack 5

**Comment by calebeby** [comment]
So vite works (really well!!)

Getting twing to work was a big pain (but it was for webpack too), but it works now. I was able to update to the latest twing which is async.

I'm ironing out some minor issues but I am planning to send a PR today hopefully!

**Comment by calebeby** [comment]
Gonna close this and assign myself to https://github.com/cloudfour/cloudfour.com-patterns/issues/1403 instead.
