### ISSUE TITLE
Use ARIA to hide ellipsis in Pagination component?

### ISSUE THREAD

**Issue by gerardo-rodriguez** [cloudfour/cloudfour.com-patterns#1977]
When I was using VoiceOver, it read "ellipses" to me when I got to the pagination UI. I didn't find that very helpful/useful. Should we `aria-hidden` it?

<img width="1436" alt="Screen Shot 2022-07-26 at 7 50 41 AM" src="https://user-images.githubusercontent.com/459757/181039155-d6d4e5d9-3d35-4843-b584-c343ed94357a.png">

**Comment by tylersticka** [comment]
Seems like a small and reasonable suggestion.
