### ISSUE TITLE
The Sky Nav should animate open/closed at smaller viewports

### ISSUE THREAD

**Issue by gerardo-rodriguez** [cloudfour/cloudfour.com-patterns#1984]
Regression?

Left: https://cloudfour-patterns.netlify.app/iframe.html?args=&id=components-sky-nav--dark&viewMode=story
Right: https://c4dev.wpengine.com

Notice on the left how the content below the nav also animates down/up.

Notice on the right how the content snaps down/up instead.

![sky-nav](https://user-images.githubusercontent.com/459757/181285498-db5b0413-c202-4621-b7dd-8414dcb06cbe.gif)

**Comment by tylersticka** [comment]
@gerardo-rodriguez Definitely a critical bug, good catch.

**Comment by gerardo-rodriguez** [comment]
@tylersticka Thanks for assigning the issue to me. I forgot to do so. 🙃
