### ISSUE TITLE
Should the footer keyboard focus styles be different than the rest of the site?

### ISSUE THREAD

**Issue by gerardo-rodriguez** [cloudfour/cloudfour.com-patterns#1987]
The footer is the only area that has a different keyboard focus style. Intentional?

![focus](https://user-images.githubusercontent.com/459757/181622166-fef42a4c-6870-44e9-bde7-8d279d4d3e29.gif)

**Comment by tylersticka** [comment]
@gerardo-rodriguez It's less a matter of the footer having different focus styles from everything else than it is the footer using default links, more like page or article content.

We may consider designing site-wide default focus styles once we decide it's time to move away from a `:focus-visible` polyfill.
