### ISSUE TITLE
Code blocks in comments have too much negative margin

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#1997]
Code blocks inside of comments seem to be extending too far. In this screenshot I'm comparing the edges of the short bio in [this article](https://cloudfour.com/thinks/css-circles/) with the edges of the comment:

<img width="1052" alt="Screen Shot 2022-08-03 at 11 53 49 AM" src="https://user-images.githubusercontent.com/69633/182687416-3607229d-7695-4731-958c-57d6a17fc6ac.png">

At small sizes this causes the code block to extend past the viewport edge:

<img width="409" alt="Screen Shot 2022-08-03 at 11 56 26 AM" src="https://user-images.githubusercontent.com/69633/182687545-183e9b62-e4b4-40f4-85ba-861eac7a3acc.png">

I'm open to ideas on how to adjust for this context.

(Thanks @spaceninja for spotting this one.)

**Comment by spaceninja** [comment]
Turns out this was only affecting code blocks in comments on legacy posts. Fixing it by better scoping the styles.
