### ISSUE TITLE
Directional border utilities

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#2001]
[Our border utilities](https://cloudfour-patterns.netlify.app/?path=/docs/utilities-border--small-default) do not have options for setting borders on individual edges. The old `u-borderTop` utility is still being used [in a recent article series](https://cloudfour.com/thinks/web-design-tool-wish-list/#this-article-is-part-5-of-a-series-on-design-tools-in-a-design-system-world%3A), so we should probably have an equivalent available before the next article goes forward (unless [the Gutenberg separator block is sufficient](https://cloudfour-patterns.netlify.app/?path=/docs/vendor-wordpress-core-blocks--separator)).

**Comment by spaceninja** [comment]
After testing the Gutenberg separator block, I think it serves the purpose:

![Image](https://user-images.githubusercontent.com/257309/186226540-547e0dcb-34b2-4912-9d86-2f76d1693531.png)

I'm going to move this to "in review" and assign it to Tyler so he can confirm when he comes back.

**Comment by megnotarte** [comment]
I wonder if @Paul-Hebert or @aileenjeffries or @gerardo-rodriguez could review. I don't want to wait if we don't have to.

**Comment by Paul-Hebert** [comment]
I _think_ the separator block is sufficient. AFAICT there are two differences:

- Slightly different color/thickness but they both look fine.
- Different semantic meaning. The separator block adds a horizontal rule. But, I think a horizontal rule is fine here? It may not be necessary if it's followed by a heading but I don't think it's wrong.

This seems fine to me, especially if we have other tasks in the backlog to further optimize the article series experience

**Comment by gerardo-rodriguez** [comment]
I agree with @Paul-Hebert!

**Comment by spaceninja** [comment]
👍  Sounds good! I'm marking this as "done."
