### ISSUE TITLE
Image block captions should be able to extend past the width of the image

### ISSUE THREAD

**Issue by gerardo-rodriguez** [cloudfour/cloudfour.com-patterns#2019]
Right now, the layout is a bit funky as the width of the caption is restrained to the width of the image.

<img width="345" alt="Screen Shot 2022-08-23 at 4 41 01 PM" src="https://user-images.githubusercontent.com/459757/186285139-85e9e322-277c-4719-8141-2b9b88779c5a.png">

**Comment by tylersticka** [comment]
@gerardo-rodriguez Can you provide more context or a link? I'm having trouble understanding the issue from the screenshot.

**Comment by gerardo-rodriguez** [comment]
@tylersticka Sure thing!

There is much more horizontal room for the caption, but it's restrained to the width of its image.

<img width="1392" alt="Screen Shot 2022-09-12 at 11 46 54 AM" src="https://user-images.githubusercontent.com/459757/189732403-05080989-df10-4395-86c9-7041e6566f5c.png">

**Comment by gerardo-rodriguez** [comment]
For comparison, this caption extends past the width of its image.

<img width="1392" alt="Screen Shot 2022-09-12 at 11 51 19 AM" src="https://user-images.githubusercontent.com/459757/189733274-20f1c5d3-12ad-4a7a-b819-b822f1e46c95.png">

Article: https://cloudfour.com/thinks/responsive-design-process-that-works/
