### ISSUE TITLE
Add ability to limit video width

### ISSUE THREAD

**Issue by gerardo-rodriguez** [cloudfour/cloudfour.com-patterns#2020]
When I add a video using the Video block, the video is the full width of the text container, and I don't need it to be full width.

<img width="1597" alt="Screen Shot 2022-08-23 at 4 47 30 PM" src="https://user-images.githubusercontent.com/459757/186285494-10baec53-fa77-40a9-a533-f982296186f2.png">

**Comment by tylersticka** [comment]
@gerardo-rodriguez Is this still the case if you choose "center" alignment for the video?

**Comment by gerardo-rodriguez** [comment]
@tylersticka Correct, the video is still much too wide even if I choose "Align center."

<img width="1392" alt="Screen Shot 2022-09-12 at 11 57 19 AM" src="https://user-images.githubusercontent.com/459757/189734075-244443e2-c12b-41cb-b41d-5dfac53210d8.png">

**Comment by tylersticka** [comment]
So I've confirmed that the expected alignment options are working as intended:

- Default: Fills gutters
- Wide: Expands beyond gutters
- Center: Only fills content area

If you want to make it narrower than that, you have two options:

1. Expand the "Advanced" block settings and use classes to adjust. [Our sizing utilities](https://cloudfour-patterns.netlify.app/?path=/docs/utilities-size--inline-size-width) seem to work well.
2. Use a "Custom HTML" block instead.

Unfortunately there aren't any additional size controls for this block, and I think that's outside the scope of this project to add.
