### ISSUE TITLE
Media-text block not handling most common use case very well

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#2146]
We have styles in support of WordPress's core "Media Text" block, but our example seems really specific: https://cloudfour-patterns.netlify.app/?path=/story/vendor-wordpress-core-blocks--media-text

In practice, it seems to behave rather strangely. Here is a screenshot from a draft by @Paul-Hebert where he attempted to use it to show the Pleasantest logo to the side of some sidebar content:

<img width="1503" alt="image" src="https://user-images.githubusercontent.com/69633/223180971-a65fde54-e1e9-47bd-ac89-27e0be0fb2f2.png">

**Comment by Paul-Hebert** [comment]
Thanks!
