### ISSUE TITLE
Support line numbers in code snippets

### ISSUE THREAD

**Issue by megnotarte** [cloudfour/cloudfour.com-patterns#268]
Some of our current posts include line numbers in the code snippets (http://blog.cloudfour.com/getting-all-javascript-into-the-footer-in-wordpress-not-so-fast-buster/). Looks like there might be a prism plugin that will support this. 

Not urgent at all. Just wanted to note this.

**Comment by tylersticka** [comment]
If we do this, we should definitely make it opt-in by the post author. Anyone who reads our posts via RSS, email, etc. won't see them, so it's a bad idea to depend on them.

**Comment by tylersticka** [comment]
Closing this because it hasn't come up in any recent posts, and I'm unconvinced it's right for the design of our blog! 🙈
