### ISSUE TITLE
hyphens: auto in Firefox

### ISSUE THREAD

**Issue by aileenjeffries** [cloudfour/cloudfour.com-patterns#269]
I noticed that hyphens is set to auto in our body definition. Firefox take this as all the excuse it needs to put hyphens everywhere. I think this makes things harder to read and @megnotarte agrees with me. Can we just take this out or is there a reason it is there? 

<img width="938" alt="screen shot 2016-06-30 at 12 48 37 pm" src="https://cloud.githubusercontent.com/assets/1242871/16502141/c10703f6-3ec1-11e6-8d19-1e18374b3552.png">

**Comment by tylersticka** [comment]
Yeah, I agree. Hyphenation plus non-justified text is doing it wrong.
