### ISSUE TITLE
Blog post: Image is overlapping author bio section on post detail

### ISSUE THREAD

**Issue by megnotarte** [cloudfour/cloudfour.com-patterns#270]
@tylersticka says we need to add the `.u-cf` class to the container so this doesn't happen: 
![screen shot 2016-06-30 at 2 53 48 pm](https://cloud.githubusercontent.com/assets/66242/16505553/77bdd25e-3ed2-11e6-8889-9e3146b2249f.png)

**Comment by tylersticka** [comment]
Fixed in the pattern library, still needs to be addressed in the theme (working on that now).
