### ISSUE TITLE
IE 11: Case study images are smaller than expected

### ISSUE THREAD

**Issue by megnotarte** [cloudfour/cloudfour.com-patterns#283]
http://c4site.staging.wpengine.com/made/

![bs_win10_ie_11 0](https://cloud.githubusercontent.com/assets/66242/16637005/a24925a6-4390-11e6-9450-d72a305838e8.jpg)

**Comment by tylersticka** [comment]
Adorbs 👶

**Comment by megnotarte** [comment]
I think this is a problem with the `WorkImage` class. I see it here as well: 
![bs_win10_ie_11 0 2](https://cloud.githubusercontent.com/assets/66242/16637129/b17e7926-4391-11e6-8c76-fa2a094d987d.jpg)

**Comment by tylersticka** [comment]
It's just mobile-optimized. :trollface:

**Comment by nicolemors** [comment]
The small screen is in the wrong location and neither is tilted as well.
