### ISSUE TITLE
IE 11: Labs page text is vertical instead of horizontal

### ISSUE THREAD

**Issue by megnotarte** [cloudfour/cloudfour.com-patterns#284]
http://c4site.staging.wpengine.com/contributes/

![bs_win10_ie_11 0 1](https://cloud.githubusercontent.com/assets/66242/16637069/28db9e46-4391-11e6-866f-bb82bc0d68dd.jpg)

**Comment by tylersticka** [comment]
And there's something _wrong_ with this, you say? 😂
