### ISSUE TITLE
Events overlap, probably should be top aligned

### ISSUE THREAD

**Issue by grigs** [cloudfour/cloudfour.com-patterns#288]
http://c4site.staging.wpengine.com/presents/
Event content overlaps as shown. Also, at other breakpoints, the alignment looks odd when the date box is vertically centered and the text next to it is longer.

![screen shot 2016-07-07 at 3 38 31 pm](https://cloud.githubusercontent.com/assets/804237/16694410/e83de6be-44ee-11e6-9e62-96acf4155f69.png)

**Comment by tylersticka** [comment]
> Also, at other breakpoints, the alignment looks odd when the date box is vertically centered and the text next to it is longer.

It looked even weirder the other way around.
