### ISSUE TITLE
Events don't handle ranges spanning months well

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#291]
October 31st through 2nd 😆 

<img width="351" alt="screen shot 2016-07-08 at 12 06 04 pm" src="https://cloud.githubusercontent.com/assets/69633/16698692/7027dee4-4504-11e6-900d-d0dbd42123c9.png">

**Comment by aileenjeffries** [comment]
We discussed this staff today - for now, we'll just leave it up to the person adding the event to only input a start day if the event spans months, worry about a real solution later.

**Comment by tylersticka** [comment]
Closing this in favor of cloudfour/cloudfour.com-wp#276
