### ISSUE TITLE
iPhone 6: device list cut off

### ISSUE THREAD

**Issue by megnotarte** [cloudfour/cloudfour.com-patterns#301]
iPhone 6, safari

http://c4site.staging.wpengine.com/portland-device-lab/

![img_8062](https://cloud.githubusercontent.com/assets/66242/16746193/13614a76-476e-11e6-97c5-c1eb4d6e40ae.png)

**Comment by tylersticka** [comment]
Might need an `overflow: auto;` option (or default) for `Table`

**Comment by saralohr** [comment]
@tylersticka
