### ISSUE TITLE
Galaxy s7, iPhone 6: blog post code snippets are forcing horizontal scroll

### ISSUE THREAD

**Issue by megnotarte** [cloudfour/cloudfour.com-patterns#302]
Can reproduce on safari on iPhone 6, as well as Chrome on Galaxy S7 (browserstack), but not regular ol' OSX Safari
![bs_realdroid_mobile_samsung galaxy s7-6 0-1440x2560](https://cloud.githubusercontent.com/assets/66242/16747361/abc7c9ca-4773-11e6-9097-733cdb355633.jpg)
![img_8063](https://cloud.githubusercontent.com/assets/66242/16747389/c882bb42-4773-11e6-8873-c34500b79c4c.PNG)

**Comment by tylersticka** [comment]
@megnotarte Horizontal scroll of the whole _page_, or horizontal scroll of the code snippets?

If it's the code snippets only that are scrolling, that's intentional. If it's the whole page, that's not.

**Comment by tylersticka** [comment]
@megnotarte I feel like you answered the question I asked in my previous comment out loud, but now I can't remember what the answer was. 😅

**Comment by megnotarte** [comment]
@ty

**Comment by megnotarte** [comment]
@tylersticka Yes! I did. It is working as expected. Scrolling only the snippet.
