### ISSUE TITLE
Toolkit JS includes unused FactSlider component

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#310]
We should probably delay including `FactSlider` in our toolkit JS until we're ready to launch that feature?

(Assigning this to "Launch" milestone so we can discuss, not as a statement of priority.)

**Comment by saralohr** [comment]
@tylersticka Sure. It will probably need modified anyways to support the slide animation. I can remove it for now and we can refer back to earlier commits when we revive it.
