### ISSUE TITLE
Paragraph spacing inconcistent

### ISSUE THREAD

**Issue by mrgerardorodriguez** [cloudfour/cloudfour.com-patterns#316]
Reading through @nicolemors bio page, the paragraph spacing between each paragraph is inconsistent. 

![simulator screen shot jul 12 2016 2 53 06 pm](https://cloud.githubusercontent.com/assets/459757/16785061/d652db9e-4840-11e6-9cd5-41e6ae9bc8cf.png)

**Comment by tylersticka** [comment]
Appears to be a content issue:

<img width="839" alt="screen shot 2016-07-12 at 2 58 51 pm" src="https://cloud.githubusercontent.com/assets/69633/16785108/2e36ee68-4841-11e6-86b6-0ab0c3cbcdea.png">

**Comment by tylersticka** [comment]
✅ Fixed in the CMS
