### ISSUE TITLE
Windows tile image doesn't work

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#319]
Despite linking to [this image](https://cloudfour.com/mstile-150x150.png), which appears to resolve, on my home PC the tile image does not show up when pinning the site to start from Edge:

![tile](https://cloud.githubusercontent.com/assets/69633/16827707/042e3a9c-493e-11e6-8f40-de5b3cbd2aac.png)

The tile color is also incorrect, which makes me think the [the config](https://cloudfour.com/browserconfig.xml) isn't being picked up for some reason.

**Comment by erikjung** [comment]
```html
<meta name="msapplication-config" content="https://cloudfour.com/browserconfig.xml" />
```

Is it necessary to add this?

**Comment by tylersticka** [comment]
Not according to [Real Favicon Generator](http://realfavicongenerator.net/blog/new-favicon-package-less-is-more/), but maybe they're mistaken. 😕

**Comment by tylersticka** [comment]
Apparently only IE11 automatically downloads that file. There is an open issue marked "won't fix" on Edge: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/101636/
