### ISSUE TITLE
IE11: Easer error

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#324]
Currently in pattern library and production:

![virtualbox_ie11 - win7_18_07_2016_13_57_43](https://cloud.githubusercontent.com/assets/69633/16930114/b4e2b746-4cef-11e6-8d03-7dd5843f58d8.png)

@erikjung @mrgerardorodriguez

**Comment by erikjung** [comment]
@tylersticka Does this seem like something related to the sky/nav or something related to the SVG?

**Comment by erikjung** [comment]
_Guessing the former since the SVG isn't in the pattern library._

**Comment by tylersticka** [comment]
@erikjung Sky/nav

**Comment by erikjung** [comment]
Closed via #328
