### ISSUE TITLE
Windows: Nav lacks right margin at ~ 1024

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#332]
The type rendering in IE11 (and probably Edge) means the text is a little wider on that platform. @aileenjeffries' recent nav updates (#318) have resulted in a loss of right-hand margin when the nav first expands to a single line:

![virtualbox_ie11 - win7_19_07_2016_13_25_12](https://cloud.githubusercontent.com/assets/69633/16965363/8c22e61c-4db4-11e6-81ae-beebada8e7e5.png)

Luckily the nav items are never inaccessible, and there's no horizontal scroll or anything, it just looks a little funny.

**Comment by tylersticka** [comment]
I think I'm actually going to chalk this one up to IE.

While there's [a long and storied history](http://www.456bereastreet.com/archive/201301/media_query_width_and_vertical_scrollbars/) when it comes to media queries and vertical scrollbars, I'm just not seeing this problem anywhere else... including Edge or Firefox.

Increasing the breakpoint the `--Sky-nav-full-viewport` breakpoint from `56em` to `67em` solves the problem, but at the expense of a certain popular tablet resolution's nav in landscape.

Given that Edge is the future, the page is still completely functional, and the change would make the experience worse in other browsers, I'm going to label this as `won't fix` for now.

**Comment by aileenjeffries** [comment]
Just catching up on this, @tylersticka. I'm fine with the won't fix label since it is totally usable, it just looks a little weird. But, I wonder if bumping `--Sky-nav-full-viewport` up just a bit, not to 67em but something like 58em or 60em would do the trick?

**Comment by tylersticka** [comment]
> But, I wonder if bumping --Sky-nav-full-viewport up just a bit, not to 67em but something like 58em or 60em would do the trick?

It would make it less off. You're welcome to re-open if you'd like to implement a compromise solution (I felt a little funny doing it).
