### ISSUE TITLE
CodePen (possibly more?) too short in blog posts due to height: 100%

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#338]
We added a base `height: 100%;` rule to `iframe` as part of #281.

Unfortunately, this is overriding `height` attributes we want to keep around. Specifically, I can't get CodePen embeds to be taller than `150px` no matter what embed technique I use:

Example from [this post](https://cloudfour.com/thinks/breaking-out-with-viewport-units-and-calc/):

<img width="872" alt="screen shot 2016-07-25 at 11 32 00 am" src="https://cloud.githubusercontent.com/assets/69633/17112636/b41e5e20-525b-11e6-9bd6-10c0190f229b.png">

If this rule was added to make `FlexEmbed` happy, we should consider scoping it to that component instead of applying it globally.

---

@mrgerardorodriguez

**Comment by mrgerardorodriguez** [comment]
Oof, good catch @tylersticka. 

> If this rule was added to make FlexEmbed happy, we should consider scoping it to that component instead of applying it globally.

Yes.
