### ISSUE TITLE
Consolidate theme.css and theme-map.css?

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#348]
I _tried_. I _really_ tried to embrace the separation of `theme.css` and `theme-map.css`.

I just... _can't_. My brain _does not care_ about this distinction.

I've grown to envy the simplicity of a single `config.css`. I wonder if we might be able to retire `theme-map.css` or at least merge everything into a single place.

But if I'm alone, we should just stay the course. I'll live.

**Comment by saralohr** [comment]
I agree @tylersticka!

**Comment by erikjung** [comment]
@tylersticka If it's more confusing than anything, then we should simplify it.
