### ISSUE TITLE
Consider redesigning blockquotes to be more distinct in some scenarios

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#362]
Screenshot from a post currently in progress:

<img width="788" alt="screen shot 2016-09-15 at 9 03 34 am" src="https://cloud.githubusercontent.com/assets/69633/18557347/65bebc98-7b23-11e6-9fed-01436bfe7bef.png">

When I saw this, I immediately thought "weird, why is that unordered list italicized?" The indentation wasn't enough to clue me in on the blockquotedness of it.

We might benefit from some indicator, however subtle. An example [from Medium](https://stories.buffer.com/why-facebook-is-blue-ea8b44016ab2#.az41ey5hl):

<img width="766" alt="screen shot 2016-09-15 at 9 06 04 am" src="https://cloud.githubusercontent.com/assets/69633/18557417/b6789b0e-7b23-11e6-9f76-25927db233de.png">

**Comment by gerardo-rodriguez** [comment]
+1
