### ISSUE TITLE
Idea: Progressively enhance footnotes with tooltip/popover approach

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#364]
I mentioned recently to @grigs that I tend not to read footnotes because I don't like to skip back and forth, and I assume if it were important to the article it would be part of the actual article.

I realized today that I _do_ actually read the footnotes... if I'm reading in Feedbin, which (like a few other sites I've seen) enhances the footnote citation links to allow for a popover reading of the contents:

<img width="706" alt="screen shot 2016-09-22 at 1 30 22 pm" src="https://cloud.githubusercontent.com/assets/69633/18765081/fff2000e-80c8-11e6-9f75-e56902ae450a.png">

The traditional footnotes are still maintained at the bottom of the post, which I find nice... I can use the tooltips if I want to, or I can regard the footnotes as I would a print article:

<img width="662" alt="screen shot 2016-09-22 at 1 32 40 pm" src="https://cloud.githubusercontent.com/assets/69633/18765108/1a01a166-80c9-11e6-8921-f4ab01076389.png">

You may recall that a similar concept was [part of the original element collage exercise](https://cloudfour.com/thinks/element-collages-are-fun/), but it wasn't implemented for two reasons:
1. My collage implemented a sort of "push-down" approach, which was _gnarly_ to build in practice for any footnotes in the middle of paragraphs!
2. A traditional "pop-over" footnote was difficult to develop without knowing the WordPress markup requirements.

Anyway, this would require some JavaScript prowess to execute on, and maybe no one else likes the idea. Just figured I'd make note of it here for future discussion. 😄

**Comment by gerardo-rodriguez** [comment]
I will neither agree nor disagree, instead, only comment that I do read the footnotes in our articles and I that I do click down, then click back up using the given links. 

This experience is similar to how I read when using the iBooks app, which perhaps is why I'm used to it. It links me out to a different page, or footnote, etc. then offers me "back to (wherever I was at)" link. 

Again, not trying to push the conversation either way, just noting my experience. :)

**Comment by tylersticka** [comment]
I've grown fond of the way we're doing it, gonna close this.
