### ISSUE TITLE
make the close button in new message pattern do something

### ISSUE THREAD

**Issue by aileenjeffries** [cloudfour/cloudfour.com-patterns#366]
I just merged in a new message pattern that will be used for an offline notification. There's an option to have a close "x" on the message, but currently, it doesn't do anything. I'm thinking some little bit of JS is needed here. 

Once it is in there, I will probably want to add some css to create a more graceful transition to `display: none`. But, I can do that once the JS is available.

**Comment by gerardo-rodriguez** [comment]
@erikjung Do you know if this has been implemented? I thought I saw an "x" button that closes the offline message on the live site.

**Comment by erikjung** [comment]
@aileenjeffries @gerardo-rodriguez It seems like the JS for this can be implemented as a generic utility that could apply to any "closable" element.

For example:

```js
document.querySelectorAll('[data-action=close]').forEach(el => {
  el.addEventListener('click', event => {
    const target = document.getElementById(el.dataset.target);
    target.remove();
    event.preventDefault();
  });
});
```

(http://s.codepen.io/erikjung/debug/JbLrxm)

**Comment by erikjung** [comment]
@gerardo-rodriguez 

> Do you know if this has been implemented? I thought I saw an "x" button that closes the offline message on the live site.

Oh, yes. It's only implemented on the site repo, not in the patterns.
