### ISSUE TITLE
Not enough contrast for accessibility

### ISSUE THREAD

**Issue by grigs** [cloudfour/cloudfour.com-patterns#369]
I had noticed that Lighthouse had complained about some accessibility issues on our site. I used tota11y to find the the following:

<img width="1259" alt="screen shot 2016-11-02 at 1 22 27 pm" src="https://cloud.githubusercontent.com/assets/804237/19946002/ce3e935e-a0ff-11e6-8482-1c2914b37bef.png">

I'm a bit surprised by this because they all look they have sufficient contrast, but I trust the math more than my eyes.

**Comment by tylersticka** [comment]
An instance of this came up recently: https://github.com/cloudfour/cloudfour.com-patterns/pull/365#discussion_r81851388

**Comment by tylersticka** [comment]
I feel I've addressed this as best as I can in #402, but see that issue for an overview of a couple other potential issues.

I'm going to close this, we can open individual issues for specific problem areas in the future.
