### ISSUE TITLE
Service worker makes local development harder

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#401]
I'm working on resolving a few CSS issues, but the service worker seems to be have cached `toolkit.css` and insists on serving that up instead, which means I only see changes that BrowserSync streams into the browser. If I refresh the whole page or load a new page, I have to save one of my stylesheets to see my changes reflected.

**Comment by erikjung** [comment]
I usually check "Bypass for network":

![screen shot 2017-03-22 at 1 36 58 pm](https://cloud.githubusercontent.com/assets/61204/24219676/e4dc9660-0f04-11e7-9aa7-fe77047da252.png)
