### ISSUE TITLE
Restrict animation when user prefers reduced motion

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#416]
From [An Introduction to the Reduced Motion Media Query](https://css-tricks.com/introduction-reduced-motion-media-query/):

> Safari 10.1 introduces the [Reduced Motion Media Query](https://developer.apple.com/library/prerelease/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_10_1.html#//apple_ref/doc/uid/TP40014305-CH12-DontLinkElementID_60). It is a non-vendor-prefixed declaration that allows developers to “create styles that avoid large areas of motion for users that specify a preference for reduced motion in System Preferences.”

Our narrow-screen menu animation and home-screen animation already have fallbacks to work without JavaScript. We could theoretically piggy-back on that existing functionality, using `window.matchMedia('prefers-reduced-motion')` to abort animation.

**Comment by alexcarpenter** [comment]
@tylersticka depending on how your animations are handled, since you are making use of CSS variables you can support reduced motion within your CSS.

![](https://pbs.twimg.com/media/DFSWPRxU0AEiIbj.jpg)

Reference: https://twitter.com/i/web/status/888500276847562752

**Comment by tylersticka** [comment]
Closing this issue as it will be resolved in the new version of the site.
