### ISSUE TITLE
Footnote design steal too much focus

### ISSUE THREAD

**Issue by megnotarte** [cloudfour/cloudfour.com-patterns#428]
It feels like the footnote design is draws too much focus when reading an article. I'm _too_ drawn to that content, which is supposed to be subservient of the actual inline page content by definition.

**Comment by derekshirk** [comment]
@megnotarte is this what you are referring to as the "footnote design?"

<img width="838" alt="screen shot 2017-10-05 at 11 42 32 am" src="https://user-images.githubusercontent.com/1427548/31246612-c1eb251e-a9c2-11e7-9676-310ae2fbec0a.png">

**Comment by megnotarte** [comment]
Correct!

**Comment by tylersticka** [comment]
This change is now live 🎉
