### ISSUE TITLE
Define pattern folder structure

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#465]
It's important we agree on an ideal structure for our design system.

Our patterns may include the following:

- Design tokens in YAML or similar format with accompanying documentation (color palettes, etc.)
- Self-contained components with some combination of Twig templates, CSS and/or JavaScript with accompanying documentation
- Patterns containing only one of those elements (just CSS, just JavaScript, etc.) with accompanying documentation
- Static assets like fonts, icons or images with accompanying documentation
- Bundles of these elements that work together
- Prototypes _not_ necessarily intended for direct consumption by other projects

I've included a couple of options to consider below, but I'd love to hear opinions from others on what they think makes sense or what they would find most intuitive.

## Parallel packages

Inspired by [Material components](https://github.com/material-components/material-components-web) and [Lerna](https://lerna.js.org/). Packages are not deeply organized, they are treated as parallel things.

```
.
├── package.json
└── packages
    ├── button
    │   ├── button.js
    │   ├── button.scss
    │   ├── button.stories.mdx
    │   └── button.twig
    ├── color
    │   ├── color.stories.mdx
    │   └── color.yml
    ├── fonts
    └── icons
```

## Organized by category

Inspired by [Salesforce Lightning](https://github.com/salesforce-ux/design-system/tree/master/ui) and various Storybook tutorials.

```
.
├── package.json
└── src
    ├── assets
    │   ├── fonts
    │   └── icons
    ├── components
    │   └── button
    │       ├── button.js
    │       ├── button.scss
    │       ├── button.stories.mdx
    │       └── button.twig
    └── tokens
        ├── color.stories.mdx
        └── color.yml
```

---

@cloudfour/design @cloudfour/dev

**Comment by Paul-Hebert** [comment]
I definitely like each pattern having all its assets and documentation in a single folder, but it seems like either option does that.

My gut feeling is that some sort of organizational structure would be helpful for a couple reasons:
- Easier to organize content when we display it in the pattern library, since we could use directory structure
- Easier for devs to find the files they're looking for.

Because of that I'd lean towards a Sales Force style setup

**Comment by tylersticka** [comment]
I agree. Having a more organized structure gives us wiggle room to define stuff more clearly. And unlike Material, we'll have some things (icons, fonts) that are _clearly_ different from other things (like components).
