### ISSUE TITLE
Media Objects Pattern(s)

### ISSUE THREAD

**Issue by dromo77** [cloudfour/cloudfour.com-patterns#474]
Create a pattern for displaying an image with descriptive content. 

<img width="223" alt="media objects" src="https://user-images.githubusercontent.com/42841342/74986765-924c0980-53ee-11ea-85b2-aa03736558d1.png">

**Comment by tylersticka** [comment]
This pattern may seem simple, but we should take into consideration content order! If there's a heading, can that go first? If the whole element is linked, how best should we structure that?
