### ISSUE TITLE
Button Pattern

### ISSUE THREAD

**Issue by dromo77** [cloudfour/cloudfour.com-patterns#475]
Create a button pattern. We currently use several different buttons that vary in color, width, and use of iconography.

<img width="642" alt="buttons" src="https://user-images.githubusercontent.com/42841342/74987773-db04c200-53f0-11ea-8fc0-9679e287cf10.png">

**Comment by tylersticka** [comment]
This pattern should coordinate with other form patterns to make sure inputs and buttons look good together.

Other considerations:

- Let's really showcase our ability to [design excellent, accessible button states](https://cloudfour.com/thinks/designing-button-states/)!
- If we are worried our focus states are too insistent, we should [consider a `focus-visible` polyfill](https://github.com/WICG/focus-visible).
- Can we use `filter` to simplify hover/active states and `transform` to give them a bit of visual delight?
- Let's consider re-balancing our border widths relative to our font weight.
