### ISSUE TITLE
Grid/layout patterns

### ISSUE THREAD

**Issue by dromo77** [cloudfour/cloudfour.com-patterns#477]
Create a grid system that can be used to layout content.

<img width="636" alt="grids" src="https://user-images.githubusercontent.com/42841342/74988623-1d2f0300-53f3-11ea-8f7d-1f1fd05db3ca.png">

**Comment by tylersticka** [comment]
I don't know if we _should_ have one big "Grid" pattern anymore!

Maybe in a world with CSS Grid Layout, we can have different layout patterns for different use cases?

Perhaps we can _start_ with our article listing, which I think would benefit the most from CSS Grid! What cool things can we do to surface illustrations where available, to support articles of various titles, etc.?

**Comment by tylersticka** [comment]
We've decided to add layout object patterns as needed for as long as possible rather than creating a thin class-based expression of CSS Grid Layout to satisfy our old habits.
