### ISSUE TITLE
Pagination pattern

### ISSUE THREAD

**Issue by dromo77** [cloudfour/cloudfour.com-patterns#478]
<img width="805" alt="Pagination" src="https://user-images.githubusercontent.com/42841342/74988980-1654c000-53f4-11ea-9614-5e5918cfedd4.png">

**Comment by tylersticka** [comment]
We should reexamine the accessibility of this pattern's markup as well as opportunities to simplify integration with our WordPress theme.

**Comment by tylersticka** [comment]
I'd also like for the "next" and "back" affordances to feel more interactive. I tried to accomplish this via a border in [one of my prototypes](https://deploy-preview-631--cloudfour-patterns.netlify.app/iframe.html?id=prototypes-articles--tyler-b): 

<img width="1640" alt="Screen Shot 2020-04-28 at 10 55 18 AM" src="https://user-images.githubusercontent.com/69633/80520784-c7209380-893e-11ea-801f-5bcde701ccc5.png">
