### ISSUE TITLE
Site header pattern(s)

### ISSUE THREAD

**Issue by dromo77** [cloudfour/cloudfour.com-patterns#479]
Create a site header pattern to be used throughout the site.

<img width="1423" alt="site header" src="https://user-images.githubusercontent.com/42841342/74989345-f7a2f900-53f4-11ea-8850-bfce75cbaee9.png">

**Comment by tylersticka** [comment]
- We should maintain our "skip to main content" behavior.
- The animation should respect `prefers-reduced-motion`.
- The current animation throws `will-change` on the whole document, which is not ideal.
- We should aim for as smooth an animation as possible (ideally 60fps).

**Comment by tylersticka** [comment]
## CSS To-dos

- [ ] Stack at small screens
- [ ] Two rows breakpoint
- [ ] Single row breakpoint
- [ ] Mouse effects
- [ ] Keyboard effects
- [ ] Improve alignment
- [ ] Reconcile with theming strategy

**Comment by tylersticka** [comment]
I'm going to close this issue and open a new one for the remaining development work.
