### ISSUE TITLE
Revised banner design element

### ISSUE THREAD

**Issue by dromo77** [cloudfour/cloudfour.com-patterns#481]
Create a banner(hero image) pattern that appears at the top of every page. Some of the banners have images or animation and others do not.

<img width="638" alt="banners" src="https://user-images.githubusercontent.com/42841342/74989607-bc54fa00-53f5-11ea-8b38-8ace6dbad866.png">

**Comment by tylersticka** [comment]
Needs to coordinate well with #479.

Should use our typography refinements (#470) to feel more current.

Reduce repetitive cloud cover, go with something that is more of an accent.

**Comment by dromo77** [comment]
I started work on the banner pattern, but realized it might be beneficial to have a container pattern first. I'm assuming the banner will live inside the container pattern or work with the container pattern in some way to provide the banner with `max-width` and `margin` attributes. If that is the case, I think it would be helpful to be able to use the container pattern with the banner pattern. @tylersticka What do you think, does it make sense to work on the container pattern #571 first?

**Comment by tylersticka** [comment]
@dromo77 I imagine it's true that this pattern will actually be a combination of patterns. Just looking at the screenshots, I can see the following possibilities:

- Blue/dark theme (already done)
- Container with clouds of some sort (is this a theme modifier? a new pattern?)
- Content container (what you're describing)
- Typographic patterns, illustrations, content, etc. (hopefully we can re-use illustrations from before)
- Probably others I'm forgetting

So it's perfectly acceptable to create new issues or create multiple patterns for this single issue. And if containers are the next logical step for your process, then go make some containers! 🙌

**Comment by tylersticka** [comment]
Some revised scope for this issue based on our meeting this morning: I'd really like to focus on a revised cloud cover design that takes into account the following:

- Avoids repetition if possible to decrease possibility of horizontal/vertical artifacts in some browsers at different zoom levels.
- Takes greater advantage of space at wider viewports.
- Does not cover entire bottom of container to avoid points of tension with rectangular content below.
- Does not immediately appear to be a butt. 🍑

**Comment by aileenjeffries** [comment]
@tylersticka I'm ready to move out of Illustrator and into Storybook with my cloud divider. Where should I add it? As a prototype, like Articles? Or as a modifier on the container object?

**Comment by tylersticka** [comment]
@aileenjeffries Hooray!

If your goal is to test how it will feel in a browser and get feedback on that (since we've only seen screenshots so far), then a prototype might be the best approach? But I'm open to whatever gets us to something we can critique on devices most smoothly.
