### ISSUE TITLE
Article header pattern

### ISSUE THREAD

**Issue by dromo77** [cloudfour/cloudfour.com-patterns#483]
The heading appears at the beginning of every article and includes the title, author, and date published.

<img width="746" alt="article heading" src="https://user-images.githubusercontent.com/42841342/74991196-22dc1700-53fa-11ea-9ea0-0ae4d639dd93.png">

**Comment by Paul-Hebert** [comment]
A lot of our articles have a heading immediately followed by a large splash graphic. I wonder if there's an opportunity for us to design some sort of cool banner layout for posts with titles and graphics. (I'm not sure what this would look like, but seeing this issue pop up after #482 made the idea occur to me.)

**Comment by dromo77** [comment]
It's definitely something to think about when we work on this pattern 👍

**Comment by tylersticka** [comment]
Should also coordinate with #481 

Our previous logic was that top-level sections had headings _above_ the cloud cover, then deeper pages would be _below_, like you were descending deeper into the site.

**Comment by tylersticka** [comment]
Closing this issue because I think any necessary patterns will be generated by article prototyping steps.
