### ISSUE TITLE
Callout pattern

### ISSUE THREAD

**Issue by dromo77** [cloudfour/cloudfour.com-patterns#489]
To place emphasis on a specific piece of content we often give that content a background color. We use this pattern similarly, but with different types of content, throughout the site. The content we usually highlight is either text, a block quote with an image, or an author bio. I'm not sure if we need separate patterns for each.

<img width="635" alt="callouts" src="https://user-images.githubusercontent.com/42841342/75058482-e955eb00-548f-11ea-8601-8f9d98b35bff.png">

**Comment by tylersticka** [comment]
Perhaps this will take the form of different background colors or themed content containers? Hard to say for sure.

Maybe there's a world where #481 and this are actually different permutations of the same concept: Themed boxes?

Just food for thought! 🍟

**Comment by tylersticka** [comment]
Closing this issue because I think any distinct patterns we'll need in this regard will result from prototyping.
