### ISSUE TITLE
Input pattern(s)

### ISSUE THREAD

**Issue by dromo77** [cloudfour/cloudfour.com-patterns#490]
Create patterns for input fields.

<img width="638" alt="forms" src="https://user-images.githubusercontent.com/42841342/75058979-ddb6f400-5490-11ea-9ad0-8948a8260f37.png">

**Comment by tylersticka** [comment]
This should go hand in hand with #475 to make sure the elements feel comparable in size.

We should take extra care to avoid the "floating label" pattern in its current form because there are accessibility and obviousness concerns with that pattern.

We should also try to embrace better contrast. The unchecked box/radio state is particularly tough to spot with the current design.

**Comment by tylersticka** [comment]
I think I'm becoming a speed bump for this work, so I'm going to un-assign myself and add some tasks for this. Don't hesitate to reach out if you have questions or want to run ideas past me.

## Types
- [ ] Text
- [ ] Email
- [ ] Search
- [ ] Text Area
- [ ] Select
- [ ] Checkbox
- [ ] Radio

## States
- [ ] Default
- [ ] Focus
- [ ] Disabled
- [ ] Read-only
- [ ] Hover
- [ ] Active

## Goals, features and ideas
- [ ] Improve contrast
- [ ] Avoid "floating label" pattern (ux issues)
- [ ] Avoid "input group" pattern (never used)
- [ ] Consistent layout (dimensions, border widths, etc.) with buttons (consider using design tokens to share values)
- [ ] Distinct appearance from buttons
- [ ] Explore using `text-indent` so overflow passes over padding
- [ ] Consider design of labels (maybe prototype a comment form?)
- [ ] Support dark theme

**Comment by tylersticka** [comment]
Helpful reading: https://css-tricks.com/custom-styling-form-inputs-with-modern-css-features/

**Comment by tylersticka** [comment]
Stole a half-hour to start making progress on this today. Still work to do but having fun designing something higher contrast than before.

<img width="431" alt="Screen Shot 2020-03-27 at 4 41 57 PM" src="https://user-images.githubusercontent.com/69633/77808759-fb581a00-7049-11ea-8689-1e6e3c6df7d7.png">
