### ISSUE TITLE
Card pattern

### ISSUE THREAD

**Issue by dromo77** [cloudfour/cloudfour.com-patterns#493]
I'm calling this a card, but there may be a better name for it. This is a common grouping of elements seen throughout the site. They all look a little different, but they share similar elements: 

- An image
- Heading
- Link
- Descriptive text

<img width="1256" alt="cards" src="https://user-images.githubusercontent.com/42841342/75061099-dbef2f80-5494-11ea-8be4-81e095c4c2e5.png">

**Comment by tylersticka** [comment]
We need to take extra care with this pattern to make sure links are [implemented in an accessible way](https://adrianroselli.com/2020/02/block-links-cards-clickable-regions-etc.html) and that heading elements come first (before images).

Related: #474

**Comment by tylersticka** [comment]
@derekshirk I saw this move to "In Progress." I think that's probably premature in advance of #609 (which did not exist till a minute ago).

**Comment by derekshirk** [comment]
Sounds good! Thank you @tylersticka.

**Comment by tylersticka** [comment]
Another point of reference when it comes to implementing this in an accessible but usable way (not recommending this solution, just food for thought): https://css-tricks.com/block-links-the-search-for-a-perfect-solution/

**Comment by tylersticka** [comment]
Completed as of #1044
