### ISSUE TITLE
Messaging and alert pattern(s)

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#510]
<img width="1378" alt="Screen Shot 2020-03-02 at 2 21 01 PM" src="https://user-images.githubusercontent.com/69633/75723420-250f6280-5c91-11ea-8d18-3b90f94826a5.png">

Currently used to convey an offline state, but accessible contrast needs work.

**Comment by derekshirk** [comment]
This looks like a good first issue for me to get my feet wet with.
