### ISSUE TITLE
Improve SCSS linting

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#518]
This is one of our first projects since we've started [feeling Sassy again](https://cloudfour.com/thinks/feeling-sassy-again/). Our Stylelint config (see #507) is having some odd effects on our Sass. For example, it seems to require a line break before any @-rule, so if we `@include` a mixin at the beginning of a class it's just adding a random line break beforehand.

**Comment by calebeby** [comment]
@tylersticka Can I address this by fixing https://github.com/cloudfour/stylelint-config-cloudfour/issues/60?

I can do this using https://github.com/prettier/stylelint-config-prettier, which disables all formatting-related rules that Prettier handles.

https://prettier.io/docs/en/integrating-with-linters.html#disable-formatting-rules-2

**Comment by tylersticka** [comment]
@calebeby 

![](http://lol.tylersticka.com/noidea3.gif)

I just do what @spaceninja tells me.

**Comment by spaceninja** [comment]
@calebeby I was planning to update our stylelint config to include prettier-recommended, per the "Recommended Configuration" setting here: https://prettier.io/docs/en/integrating-with-linters.html#recommended-configuration-2

That will both disable stylelint rules that prettier covers and also run prettier as part of running stylelint.

**Comment by calebeby** [comment]
@spaceninja Is there a benefit to that over running the two tools separately (like we are doing for JS)?

**Comment by spaceninja** [comment]
I believe there would be no difference between using the recommended configuration vs running the two tools separately as part of a package.json command. I'm not married to this idea, as long as the end point is we're running prettier and linting for both CSS & JS.

That said, it is a bit cleaner and nicer:

```
"lint:css": "prettier --list-different '**/*.css' && stylelint '**/*.css'"
```

vs

```
"lint:css": "stylelint '**/*.css'"
```

**Comment by calebeby** [comment]
I was thinking we could combine the lint:css and lint:js tasks so we only run prettier once (on both js and css files)

**Comment by spaceninja** [comment]
Interesting — my gut reaction is that I like having the ability to run them separately. For example, if JS linting or CSS linting takes some time, and I'm only working on one, it's nice to have the option.

But that's maybe not a realistic use case? I imagine our linting is all pretty quick right now.

Given that approach, I agree it makes sense to keep prettier separate.

**Comment by spaceninja** [comment]
Heh, I just noticed that I have an issue filed on the stylelint config complaining about the very line-break issue Tyler mentions: https://github.com/cloudfour/stylelint-config-cloudfour/issues/6

**Comment by spaceninja** [comment]
@calebeby I'm going to jump on this. For now I'll leave Prettier as a separate task so we can optimize around it later as needed.
