### ISSUE TITLE
Should we also lint MDX files?

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#521]
Storybook Docs use `.mdx` files for defining stories. Right now, these are not being linted, which makes sense since they are not pure JavaScript.

Does it make sense to use something like [eslint-plugin-mdx](https://github.com/mdx-js/eslint-mdx) to enforce some consistency in these files?

**Comment by Paul-Hebert** [comment]
If the plugin works well I don't see any reason not to lint these mdx files.

**Comment by spaceninja** [comment]
I'd recommend using Remark rather than an eslint plugin — it's what I see being used most commonly in projects that use Markdown or MDX.

**Comment by calebeby** [comment]
The mdx eslint plugin integrates with remark

**Comment by calebeby** [comment]
The benefit of this approach is that it allows us to lint both JS expressions in .mdx files as well as markdown formatting

**Comment by spaceninja** [comment]
Actually, forget I said that. I forgot that MDX is different than Markdown, and you may want to run eslint to lint the JS bits of the MDX.

Remark is a great Markdown linter, but that's less important than linting the JS.

Sorry to muddy the water.

**Comment by spaceninja** [comment]
> The mdx eslint plugin integrates with remark

Well, perfect! :D

Thanks @calebeby

**Comment by calebeby** [comment]
@spaceninja are there certain (non-formatting) rules that you are wanting remark to enforce? Here is a list of rules it supports: https://github.com/remarkjs/remark-lint#rules

We could also use one of the presets

**Comment by spaceninja** [comment]
@calebeby let's use the recommended preset to begin with and fine-tune as needed.
