### ISSUE TITLE
Add padding to Storybook previews

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#546]
As @Paul-Hebert pointed out while reviewing #545, some wider patterns are reaching the edge of the Storybook canvas:

![](https://user-images.githubusercontent.com/5798536/76439908-5a473f00-637a-11ea-96a6-9b3340c58ed1.png)

Some ways we could address this:

- Via an add-on like [storybook-addon-paddings](https://github.com/rbardini/storybook-addon-paddings)
- Via whitespace utility classes, which we've yet to add or discuss

**Comment by tylersticka** [comment]
If we had #549, we could pipe some standard padding values to the afore-linked padding add-on. Just a thought!

**Comment by tylersticka** [comment]
I tried using the add-on, but ran into an issue: https://github.com/rbardini/storybook-addon-paddings/issues/6

**Comment by rbardini** [comment]
Hi @tylersticka! I just released [`storybook-addon-paddings@2.0.2`](https://github.com/rbardini/storybook-addon-paddings/releases/tag/v2.0.2) which should be compatible with any Storybook framework, including HTML. Feel free to give it another try, and let me know if you find any issues 😉
