### ISSUE TITLE
Allow empty lines in JS blocks in MDX?

### ISSUE THREAD

**Issue by Paul-Hebert** [cloudfour/cloudfour.com-patterns#555]
It's possible to insert JS blocks at the top of our MDX files. However, if you introduce any empty lines within JS blocks for code organization then they're treated as markdown instead of JS.

There are a few relevant issues that may be worth tracking:

https://github.com/mdx-js/mdx/issues/787
https://github.com/mdx-js/mdx/issues/195

In the meantime I'm curious if anyone has any clever ideas to help handle this.

**Comment by Paul-Hebert** [comment]
<img width="823" alt="Screen Shot 2020-03-18 at 12 15 00 PM" src="https://user-images.githubusercontent.com/5798536/76998625-a82bec00-6912-11ea-92c6-0b3920b863ee.png">

**Comment by calebeby** [comment]
Here is a fun hack:

You can put `export {}` on the line before a line you want mdx to interpret as JS


```js
export {}
console.log('hello')
```

Even more hacky (or equally hacky?)

```js
export console.log('hello')
```

Not sure if webpack will allow that one though

**Comment by Paul-Hebert** [comment]
Oh... interesting... I'm not sure how I feel about actually using that but it's good to know!

**Comment by spaceninja** [comment]
@Paul-Hebert since this is a limitation of MDX with no easy answer beside the workarounds Caleb posted, would you be okay closing this issue?

**Comment by Paul-Hebert** [comment]
Sure :+1:
