### ISSUE TITLE
Icon is cut off on non-retina display in FF and Safari

### ISSUE THREAD

**Issue by gerardo-rodriguez** [cloudfour/cloudfour.com-patterns#566]
I'm not sure if this is a high-priority issue, but I noticed the heart icon is cut off on the right side when viewing through my non-retina display at wider viewports.

It seems to only happen in the following browsers for me:
- FF 74.0
- Safari 13.0.5

## FireFox 74.0

![Screen Shot 2020-03-24 at 2 57 00 PM](https://user-images.githubusercontent.com/459757/77481660-5a672600-6de1-11ea-8d68-46478878ee4c.png)

## Safari  13.0.5

![Screen Shot 2020-03-24 at 3 10 36 PM](https://user-images.githubusercontent.com/459757/77481853-c9447f00-6de1-11ea-9bca-99a36ab73fa1.png)

**Comment by gerardo-rodriguez** [comment]
@tylersticka I wasn't sure how to properly label this issue. Please advise if I should add to the official "v-next" project or if labels need to be adjusted. Thank you! 🙂

**Comment by Paul-Hebert** [comment]
Ooh I think I've run into this before. I think we adjusted the viewbox by adding 1px to the end values and setting the start values to -1.

e.g.

`viewBox="0 0 10 10"` -> `viewBox="-1 -1 11 11"`

This gives the icons an extra couple of pixels before they're cropped. Hopefully that helps here.

**Comment by tylersticka** [comment]
Questions I'd be interested in knowing to diagnose:
- Does this happen on [the Drizzle version](https://cloudfour-patterns.netlify.com/patterns/components/icon.html)?
- Does this happen when centering is turned off? (Button has odd issues using the Storybook centered plugin, too)

**Comment by tylersticka** [comment]
> I wasn't sure how to properly label this issue. Please advise if I should add to the official "v-next" project or if labels need to be adjusted. Thank you! 🙂

@gerardo-rodriguez You did great! Thank you!

**Comment by gerardo-rodriguez** [comment]
@tylersticka Great questions!

> Does this happen on the Drizzle version?

Nope, all the icons look fine.

> Does this happen when centering is turned off? (Button has odd issues using the Storybook centered plugin, too)

I'm not sure if there is an official way of "turning off" centering but two more bits of detail:
- the icon is only cut off in the "Docs" view
- if I remove the `display: flex` declaration on the `#sb-addon-centered-wrapper` element, the icon is no longer centered and no longer cut off either 🤷‍♀ 

![Screen Shot 2020-03-24 at 3 50 28 PM](https://user-images.githubusercontent.com/459757/77484388-a4eba100-6de7-11ea-849f-ace7deb730c7.png)

**Comment by tylersticka** [comment]
So if I resize my browser to odd sizes I can _sometimes_ get this to happen even if centering is turned off. And the shape does appear to reach the horizontal viewBox bounds (as @Paul-Hebert alluded to earlier).

Arguments for bumping the `viewBox` up:

- It'll fix this bug.
- It's easy.
- It's probably not super noticeable visually.

Arguments against:

- The icon asset hasn't changed since 2016.
- We haven't noticed this bug being symptomatic in a user-facing context.
- Maybe we should eventually do a pass of _all_ our icons to adjust relative sizing, stroke widths, etc. In that case, is this premature?

Open to opinions on that.

**Comment by gerardo-rodriguez** [comment]
@tylersticka I find your arguments _against_ to be stronger. 👩‍⚖

**Comment by Paul-Hebert** [comment]
Yeah, that works for me. 👍
