### ISSUE TITLE
Numeric table headings drift from content

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#577]
After #573 was merged, tables started expanding to fill their available width. When that happened, it became more clear that the current alignment of table headings feels a bit off with numeric data. Note how the headings appear closer to the preceding cell's content:

<img width="1050" alt="Screen Shot 2020-03-31 at 8 27 46 AM" src="https://user-images.githubusercontent.com/69633/78044595-c558b580-7329-11ea-8b35-fc7686f31eff.png">

Perhaps the most obvious solution would be to right-align the headings as well, but there may be other solutions involving vertical rules that are currently unexplored.

---

See #491 

/CC @Paul-Hebert

**Comment by Paul-Hebert** [comment]
Oh yeah, good catch! I also wonder about whether the numeric columns need to be as wide as they are... If they were the width of the heading + padding then this wouldn't be an issue...

I'll try to find some time to look into this soon but if anyone else has an idea or wants to look into it first don't be shy :)
