### ISSUE TITLE
Improve sorting of Storybook sidebar

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#578]
Currently the sidebar content is sorted with "Getting Started" first (great!), followed by Components, Design Tokens, Design and Themes.

Ideally, I'd love to see these groups sorted in the following order (also including things we haven't created yet):

1. Getting Started
1. Design
1. Design Tokens
1. Objects
1. Components
1. Utilities
1. Themes
1. Third-Party
1. Prototypes

Sorting logic should _only_ apply to the top level.

**Comment by Josh68** [comment]
Hopefully, this is just some fancy sorting foo in `preview.js`, so adding a size 1. Will update if it turns out to be harder.
