### ISSUE TITLE
Set viewport add-on sizes based on breakpoint design tokens

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#580]
We have a viewport add-on installed that lets us easily test our components in Storybook at different sizes:

<img width="1120" alt="Screen Shot 2020-04-01 at 1 01 34 PM" src="https://user-images.githubusercontent.com/69633/78181274-eea43f00-7418-11ea-84ab-48d664c13f6f.png">

Now that we have design tokens for our standard breakpoints (see #570) we should consider configuring the add-on to use these sizes.

**Comment by Josh68** [comment]
https://github.com/cloudfour/cloudfour.com-patterns/pull/597
