### ISSUE TITLE
Odd double quotes and apostrophes with new variable font

### ISSUE THREAD

**Issue by Paul-Hebert** [cloudfour/cloudfour.com-patterns#610]
Tyler recently added some dummy data to the site to prototype the blog listings.

While playing with it I noticed that the double quotes and apostrophes look oddly angular and intense. I tried going in and replacing these with HTML entities for the relevant glyphs but it didn't appear to fix the double quotes.

<img width="1224" alt="Screen Shot 2020-04-09 at 1 18 25 PM" src="https://user-images.githubusercontent.com/5798536/78947960-bdacb580-7a7b-11ea-925e-02ff3d4d528f.png">
<img width="85" alt="Screen Shot 2020-04-09 at 3 48 07 PM" src="https://user-images.githubusercontent.com/5798536/78947968-c1403c80-7a7b-11ea-8ef1-69a6dbd35255.png">
<img width="37" alt="Screen Shot 2020-04-09 at 3 48 14 PM" src="https://user-images.githubusercontent.com/5798536/78947969-c1d8d300-7a7b-11ea-83fb-447d1a7ee1fd.png"> 

I saw this issue in Firefox on my macbook.

**Comment by tylersticka** [comment]
Confirmed with [FontGoggles](https://fontgoggles.org/) that these characters are missing from our font files. Time to tweak our subset!

<img width="1512" alt="Screen Shot 2020-04-09 at 4 16 27 PM" src="https://user-images.githubusercontent.com/69633/78948536-922aca80-7a7d-11ea-97eb-6882e32ccc65.png">

**Comment by tylersticka** [comment]
This is only true of the variable fonts. That's good, because it means I only have to update two files instead of ten!
