### ISSUE TITLE
Renovate does not automatically specify assignees or reviewers as configured

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#613]
The `renovate.json` config file specifies `assignees` and `reviewers`, but these are not working as expected.

It is not surprising that `assignees` is not working, because it is not possible to assign GitHub issues to teams. We can probably just remove that piece of the configuration.

For reviewers, we may be missing a prefix. [From the docs](https://docs.renovatebot.com/configuration-options/#reviewers):

> If on GitHub and assigning a team to review, use the prefix `team`:, e.g. provide a value like `team:someteam`.

---

/CC @calebeby

**Comment by tylersticka** [comment]
Renovate still does not assign reviewers correctly.

Does `team:` need `cloudfour` omitted? 🤔

**Comment by calebeby** [comment]
> Does `team:` need `cloudfour` omitted? 🤔

Maybe, we can try it

**Comment by calebeby** [comment]
#635 was merged and it works :heavy_check_mark:
