### ISSUE TITLE
CSS source maps in Storybook

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#642]
When developing in Storybook and inspecting elements, all that's ever shown is `inline:*` for the location of the CSS. This isn't very useful:

<img width="406" alt="Screen Shot 2020-04-22 at 2 26 52 PM" src="https://user-images.githubusercontent.com/69633/80035705-53e1d200-84a5-11ea-830e-1568a50daec3.png">

Ideally we could embed source maps in our output when running locally, allowing us to debug more easily. But after spending around 45 minutes attempting to troubleshoot, I was unsuccessful.

Things I tried:

- Adding `{ options: { sourceMap: true } }` to the `css-loader`, `postcss-loader` and `sass-loader` rules in our configuration.
- Removing the `postcss-loader` step entirely (and checking out an old commit) to make sure that step wasn't messing with anything (it does not seem to be).
- Changing the `config.devtool` option in `webpackFinal` (did not seem to have any perceivable effect).

I feel like I'm missing something silly, but I've spent as much time as I'm willing to at the moment.

**Comment by Josh68** [comment]
@tylersticka, I've configured a similar setup in other Webpack-based projects. Would you like me to take a look?

**Comment by tylersticka** [comment]
@Josh68 Go for it!

**Comment by Josh68** [comment]
I'm stymied, because I started with what you did in bullet-point 1, and on my end I think it's working as expected. This what you expect to see, correct, @tylersticka?

![image](https://user-images.githubusercontent.com/771447/80041769-1d5e8400-84b2-11ea-9830-ebe42e730d67.png)

**Comment by tylersticka** [comment]
That _is_ what I expect to see! If it happened that quickly I must have made some dumb mistake.

**Comment by Josh68** [comment]
I am going to quickly review the options for sourcemaps. We might want to fork the way they're handled in dev and build. That could be handled in a separate task, of course.

Currently, for development, it's already set as `devtool: '#cheap-module-source-map',`
