### ISSUE TITLE
Update icons

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#657]
I like our current icon set, but there are a few small updates they would benefit from in the short term.

## Current Source File Location

In our shared project file location, the Illustrator files for icons are in Icons ▸ Glyphs.

## Retire some icons

There are a few icons we are never using or will likely stop using that we can remove:

- [x]  **dot**: Was used by the radio pattern, which no longer exists since we never used it.
- [x] **lanyrd**: This site has been broken [since 2019](https://en.wikipedia.org/wiki/Lanyrd).
- [x] **notification:** It's unclear what this icon was meant to do that wasn't covered by **notifications**. It isn't used in any templates.

## Organization

Currently our icons sit in one folder, but I think these might benefit from some reorganization:

- [x] Original icons should sit at the root of the icons directory. These include glyphs like arrows, link, notifications, etc.
- [x] Icons representing third-party brands should be moved to a "brands" subdirectory. These include icons for publications (A List Apart, Smashing, etc.), social media websites, etc.
- [x] Our logo should be moved _out_ of icons, possibly one level up.

This organization should also be reflected in our source files, with separate files for each type of asset.

Why? I'll get to that next…

## Sizing

The biggest design opportunity with our icons is to reconcile differences in perceived visual size.

Some icons look proportionate to one another. Notice how the smaller caret (used for dropdowns) is smaller in proportion to the check mark, the same way that the ▾ character is typically rendered compared to ✔️:

<img width="322" alt="Screen Shot 2020-04-24 at 4 30 08 PM" src="https://user-images.githubusercontent.com/69633/80264394-e2428900-8648-11ea-82e5-69ae7a800998.png">

But this is not true of all icons. Notice how small the notification bell 🔔  feels in comparison to ➕ :

<img width="307" alt="Screen Shot 2020-04-24 at 4 31 37 PM" src="https://user-images.githubusercontent.com/69633/80264469-19189f00-8649-11ea-8549-43fc42e4b35e.png">

The [Material Icon Design Principles](https://material.io/design/iconography/system-icons.html#grid-and-keyline-shapes) page does a good job of illustrating some of the concepts between icon sizing and composition to promote consistency and prevent these issues.

This is also why I feel it's important to organize our icons better. By sizing them relative to each other, maybe the Lanyrd (RIP) icon (which extends dramatically into the top-left corner) wouldn't be threatening to devour the GitHub icon (which is confined to a circle):

<img width="116" alt="Screen Shot 2020-04-24 at 4 32 20 PM" src="https://user-images.githubusercontent.com/69633/80264513-436a5c80-8649-11ea-8017-75df3632c8e1.png">

Finally, the logo is used primarily as a _branding_ element (not an icon). Arbitrarily squashing it into our 24×24 grid raises three issues:

- We have to scale the element up for its primary use case, which is silly.
- Its coordinates will have more decimal points, which increases the size of the markup required to define the shape.
- Decimal points may be rounded for performance, which could result in quality loss.

So to summarize the goals here:

- [x] Resize icons as a family so they will read as _visually_ consistent, rather than simply filling the `viewBox`.
- [x] Treat logo asset as separate and don't squash it down like an icon.

## Simplify stroke colors

In our preview icon pattern, any patterns that used a stroke color instead of a fill color had to specify `stroke="currentColor"`. This is no longer the case, so it can be left off those patterns entirely.

- [x] Remove unnecessary `stroke` attributes.

## Not in scope…

- Sweeping revisions to our icon styles. We should certainly tweak things like `stroke-width` to account for the resizing, but we should stick with our current angles, our chunky hearts and envelopes, etc.
- It feels a little clunky in 2020 to be pointing people to a shared directory so they can open Illustrator and manually export SVGs. But while I'd love to explore a GitHub-style [Figma integration](https://github.blog/2018-04-12-driving-changes-from-designs/) for this, I think that's turning a modest task into a gargantuan one.

**Comment by derekshirk** [comment]
Hi @tylersticka, 

I wanted to check in quickly on the expectations regarding the re-organization of these assets. 

My understanding and assumption is that not only should these icons be organized better within the project's file structure, but the new organization should also be represented (visually) within the Storybook interface. 

![Screen Shot 2020-04-30 at 12 52 34 PM](https://user-images.githubusercontent.com/1427548/80753180-ae9cae80-8ae1-11ea-9a7c-8a6cb75e5797.png)

Is my understanding correct?

**Comment by tylersticka** [comment]
1. Correct.
1. You could. I think it would be better to keep the brands nested under icons. I could see the logo moved to a "Brand" or "Brand Elements" section where we could document things like that and illustrative elements like trees, clouds, default avatars, etc.

**Comment by derekshirk** [comment]
Awesome. Thank you for your prompt response.

**Comment by derekshirk** [comment]
**Status update:** working on the sizing section now.

**Comment by derekshirk** [comment]
Closed 😄
