### ISSUE TITLE
Add support for the <kbd> element

### ISSUE THREAD

**Issue by derekshirk** [cloudfour/cloudfour.com-patterns#669]
> The HTML Keyboard Input element (`<kbd>`) represents a span of inline text denoting textual user input from a keyboard, voice input, or any other text entry device. By convention, the user agent defaults to rendering the contents of a `<kbd>` element using its default monospace font, although this is not mandated by the HTML standard.

See: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/kbd

## Styling `<kbd>` elments

See: https://html.com/tags/kbd

**Comment by tylersticka** [comment]
@derekshirk I was originally going to style these just like `code`, but what do you think about stylizing them just a tad?

<img width="798" alt="Screen Shot 2020-05-01 at 4 47 37 PM" src="https://user-images.githubusercontent.com/69633/80849319-84272000-8bcb-11ea-9b7c-125b6b3c8ceb.png">

**Comment by derekshirk** [comment]
I love that and I agree that this deserves a bit of a unique style!

**Comment by Paul-Hebert** [comment]
I like the styling as well!
