### ISSUE TITLE
Add Testing

### ISSUE THREAD

**Issue by spaceninja** [cloudfour/cloudfour.com-patterns#701]
Pulling the testing-related tasks out of #683:

- Write tests for existing JS files in [Jest](https://jestjs.io/) and/or [Cypress](https://www.cypress.io/) with [testing-library](https://testing-library.com/)
- set up these tools as necessary

**Comment by calebeby** [comment]
Part of this task is blocked by #683, for now I'm just going to do the setup-related work that can be done before #683 is done

**Comment by spaceninja** [comment]
That makes sense. I'm hoping to have a PR up for #683 later today or early tomorrow.
