### ISSUE TITLE
Link to CONTRIBUTING from README

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#702]
At some point we moved the part of the docs describing how to run Storybook from `README.md` to `CONTRIBUTING.md`.

Because this is a new organization compared to our other projects, I keep forgetting this file exists. Apparently this isn't just me, as I recently helped a contributor who also did not find it.

Could we compromise and include a link to the contributing docs from the README as a reminder that they exist?

---

/CC @spaceninja

**Comment by spaceninja** [comment]
Oh good call. The idea was just to break it out and make it clear that README is for consumers of the pattern library. But it's totally reasonable to have a link for contributors.
