### ISSUE TITLE
Cloud Divider

### ISSUE THREAD

**Issue by haysjoey** [cloudfour/cloudfour.com-patterns#720]
I'd really like to focus on a revised cloud cover design that takes into account the following:

- Avoids repetition if possible to decrease possibility of horizontal/vertical artifacts in some browsers at different zoom levels.
- Takes greater advantage of space at wider viewports.
- Does not cover entire bottom of container to avoid points of tension with rectangular content below.
- Does not immediately appear to be a butt.

**Comment by haysjoey** [comment]
https://github.com/cloudfour/cloudfour.com-patterns/pull/717

**Comment by tylersticka** [comment]
@aileenjeffries Here are the thoughts I promised to provide earlier this morning…

At larger sizes, it seems like there's still an opportunity to improve the contrast in size between the different cloud areas and to really take advantage of the space:

![cloud-sketch](https://user-images.githubusercontent.com/69633/82367149-329ed380-99c8-11ea-9ded-8c5c1492f06b.jpg)

I also wonder if in actual use we'll want this to be symmetrical or if it would be better left to the right-hand side, where there's naturally a bit of an awkward gap currently:

<img width="1679" alt="Screen Shot 2020-05-19 at 11 58 08 AM" src="https://user-images.githubusercontent.com/69633/82367258-5e21be00-99c8-11ea-95ea-78a5b6b7708a.png">
