### ISSUE TITLE
Expand upon brand asset stories

### ISSUE THREAD

**Issue by derekshirk** [cloudfour/cloudfour.com-patterns#725]
## Overview

We currently have a single Design → Brand story. 

![Screen Shot 2020-05-20 at 9 20 17 AM](https://user-images.githubusercontent.com/1427548/82471211-3e979d80-9a7b-11ea-8f61-6c02731467b1.png)

I think we have opportunities to expand upon this beyond just our Cloud Four logo. 

For example, we could include the following: 

- [ ] Trees/skyline
- [ ] ~Team member illustrations~ (see [comments](https://github.com/cloudfour/cloudfour.com-patterns/issues/725#issuecomment-631586215) below)
- [ ] Clouds (pending further work on #720)

## Screenshots

![Screen Shot 2020-05-20 at 9 03 44 AM](https://user-images.githubusercontent.com/1427548/82471667-d8f7e100-9a7b-11ea-8973-1c9402b7b4b2.png)
Trees/Skyline

![Screen Shot 2020-05-20 at 9 04 50 AM](https://user-images.githubusercontent.com/1427548/82471697-e3b27600-9a7b-11ea-8ee6-48a95e72f030.png)
Team member illustrations

![Screen Shot 2020-05-19 at 10 07 04 AM](https://user-images.githubusercontent.com/1427548/82471718-edd47480-9a7b-11ea-9642-3594513d7729.png)
Example of WIP cloud divider

**Comment by tylersticka** [comment]
@derekshirk We should not include team member illustrations, as I consider that _content_ rather than a design asset. It's also a bit creepy to open source employee likenesses.

**Comment by derekshirk** [comment]
Thanks for commenting @tylersticka. I had similar thoughts and reservations. However I did wonder if there was anything worth documenting about the general style of our illustrations. For example: 

- Use a certain hue/saturation range for background colors
- Don't add too much details to pupils
- Etc. 

I'm not trying to argue against or make a case for including this information. I just thought I would explain my original reasoning.

**Comment by tylersticka** [comment]
That's a good idea, and I have some of that information already, but I don't know that it makes sense to prioritize in the near term compared to the other to-dos in this issue.

**Comment by tylersticka** [comment]
Closing this for now, will create more specific issues to tackle.
