### ISSUE TITLE
Overall page layout with stretchy main area

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#742]
On our current site, the default page color is silver. This means that if the page is very short, the footer will appear to stretch to meet the bottom of the viewport:

![Screenshot_2020-05-26 Page not found - Cloud Four](https://user-images.githubusercontent.com/69633/82945817-44492380-9f52-11ea-87a2-ba9764aa319b.png)

But ideally, I would prefer for the background color to stay white and for the main content area to be the thing that stretches:

![stretchy](https://user-images.githubusercontent.com/69633/82946020-7b1f3980-9f52-11ea-9306-873e7dc53a55.png)

Not only would this make our CSS easier to use in prototypes and such (since it wouldn't the background to silver), but I think it looks more balanced to not increase the footer area.

Here's a good place to start in terms of different techniques: https://css-tricks.com/couple-takes-sticky-footer/

And whoever takes on this issue might want to chat with @spaceninja about some challenges we had maintaining this behavior in a recent Vue project.

**Comment by derekshirk** [comment]
@tylersticka 

I didn't get around to looking at this issue until close to end of day, but so far I have: 

- moved it to the in-progress column
- Self assigned this task
- Sized this task (2 points)
- Reviewed [different techniques](https://css-tricks.com/couple-takes-sticky-footer/) for achieving the desired result 
- Did some quick in-browser testing with the developer tools

![cloudfour-dot-com-sticky-footer](https://user-images.githubusercontent.com/1427548/89842501-add8d700-db2a-11ea-96c7-9adf9641a7cf.gif)

Tomorrow, I plan on 

- Sharing my plan of attack with Scott to see if he has any feedback based on his prior experience with a similar request in a recent project. 
- Working on code changes required to submit a PR
- Submit a PR

**Comment by derekshirk** [comment]
When I originally picked up this card my priorities were to focus solely on front-end tasks. In order to acheive the result demonstrated above I needed to modify the markup contained in the cloudfour.com-wp repo and therefore have decided that I does not make sense to continue my effort on this issue at this time. 

Here is a basic outline of the markup and CSS I used to generated the test above: 

```html
<html>
  <body>
    <div class="o-new-content-container">
      <div class="c-sky-nav"></div>
      <main></main>
    </div>
    <footer class="c-footer-main"></footer>
  </body>
</html>
```

```css
html, 
body {
  height: 100%;
}

body {
  display: flex;
  flex-direction: column;
}

.o-new-content-container {
  flex: 1 0 auto;
}
.c-footer-main {
  flex-shrink: 0;
}
```
