### ISSUE TITLE
Adjust Renovate settings to reduce noise

### ISSUE THREAD

**Issue by emersonthis** [cloudfour/cloudfour.com-patterns#786]
We sometimes get 50+ notifications/day from Renovate. It's too much to be actionable, so we should either suppress the notifications or adjust the activity to make this more manageable. Further discussion in Slack: https://cloudfour.slack.com/archives/C04AEEVK2/p1591651399101700

cc @calebeby

**Comment by spaceninja** [comment]
I've just added the `automergeMinor` preset, which should allow Renovate to automatically merge minor and patch dependency updates. Note that we'll still get notifications for those PRs.

If those notifications become too much, we could tweak the renovate config to use `automergeType=branch` which should do the same thing without PR notifications.

**Comment by spaceninja** [comment]
@emersonthis I think @calebeby's recent changes have address this. Can we close this ticket?
