### ISSUE TITLE
Figure out how to consume design tokens in client-side JS

### ISSUE THREAD

**Issue by emersonthis** [cloudfour/cloudfour.com-patterns#787]
Related to: #718 

This issue was briefly discussed [in Slack](https://cloudfour.slack.com/archives/C04AEEVK2/p1591735057108500) in connection with implementing different behavior for the Sky Nav at different breakpoints... 

**Background**
Our design tokens live in centralized yaml files that are consumed by The Patterns. At the time of writing this, we are importing them into `scss` files. But we do not (yet) reference them directly in client-facing JavaScripts.

The tool we are currently using for abstracting tokens is [Theo](https://github.com/salesforce-ux/theo). However, Tyler expressed interest in this alternative as well: https://amzn.github.io/style-dictionary/#/

**Def of Done**
- [ ] Ability to reference a design token variable in a client-facing JavaScript file
-  ~a solution for how to _use_ `em` values in a JavascriptContext*~

\* This may be trickier than it sounds, because we're currently using fluid font sizes that scale up/down proportionally to the viewport width. So it's not as simple as multiplying by the font-size (integer) of the relevant breakpoint

**Comment by tylersticka** [comment]
I'm about to submit a PR for the first "def of done."

I've removed the second point because (a) Theo has format transformations built in and (b) I don't think we'll actually need to use them.
