### ISSUE TITLE
Resolve differences in Storybook vs. Wordpress visual presentation

### ISSUE THREAD

**Issue by derekshirk** [cloudfour/cloudfour.com-patterns#789]
I was a bit confused by this and thought opening an issue would be the easiest way to communicate what I am experiencing and ask for help. I hoped that the process of me writing this down would help me gain some clarity into the issue and sure enough it did!

## TL:DR
I believe I need to modify the changes that were introduced in #778 to update the order in which CSS is loaded for our Gutenberg previews. 

If anyone is interested in following along with the thought processes that lead me to this conclusion I am going to keep most of what I had originally intended to include in this issue below. 

---

## The issue

#778 introduced the `@wordpress/block-library` styles into our Storybook previews. 

The part that has me scratching my head a bit is, I am experiencing visual discrepancies between the visual output of what I see in Storybook vs. what I see in a local version of cloudfour.com with the same CSS. 

Example: 

When testing on a local.cloudfour.com environment I see this:

![Screen Shot 2020-06-10 at 3 40 49 PM](https://user-images.githubusercontent.com/1427548/84325995-e0695200-ab30-11ea-85f7-1e6331fee7b1.png)

That same CSS within a Storybook preview looks like this: 

![Screen Shot 2020-06-10 at 3 42 41 PM](https://user-images.githubusercontent.com/1427548/84326286-6daca680-ab31-11ea-950b-14592a79ffd6.png)

I _can_ get around this by increasing the specificity of some selectors, which also fails to adhere to our CSS guidelines and best practices, by doing this. 

Changing this: 

```css
  .wp-block-file__button,
  :not(.wp-block-file__button) {
    @include button.default;
    opacity: inherit !important; /* 1 */
  }
```

To this: 

```css
  a.wp-block-file__button,
  :not(.wp-block-file__button) {
    @include button.default;
    opacity: inherit !important; /* 1 */
  }
```

I don't want to style a selector with a tag and I don't think I should have to do that. Which leads me to believe that perhaps there is a "source order" discrepancy and the CSS is not being loaded in the same order in both environments. ~However, I have yet to be able to confirm or deny this.~

When I view source of my local WordPress install, I see the following CSS being loaded in this order: 

```html
<link rel='stylesheet' id='wp-block-library-css'  href='https://local.cloudfour.com/wp-includes/css/dist/block-library/style.min.css?ver=5.4.1' type='text/css' media='all' />
<link rel='stylesheet' id='toolkit-css'  href='https://local.cloudfour.com/wp-content/themes/cloudfour/static/main.css?ver=1589216350' type='text/css' media='all' />
<link rel='stylesheet' id='v-next-css'  href='https://local.cloudfour.com/wp-content/themes/cloudfour/static/v-next.css?ver=1591826399' type='text/css' media='all' />
```

(Where `v-next.css` is a new file I enqueued with the output of the `standalone.css` file from our new patterns)

As I mentioned above, #778 imported the `@wordpress/block-library` styles like so: 

```
import { Story, Preview, Meta } from '@storybook/addon-docs/blocks';
import codeBlockDemo from '../../design/typography/demo/code-block.twig';
import '@wordpress/block-library/build-style/style.css';
```

see: `src/vendor/wordpress/gutenberg.stories.mdx`

Based on what I can tell this is loading the Gutenberg styles after our `main.css` file. 

![Screen Shot 2020-06-10 at 4 01 04 PM](https://user-images.githubusercontent.com/1427548/84327391-0d6b3400-ab34-11ea-8790-bbc53e80c536.png)

## Where to go from here!

1. If there is an option to include the Gutenberg styles before `main.css` _and_ to only load the default WordPress styles on the Gutenberg previews, I think that would be best approach. 
1. If loading the Gutenberg styles only for Gutenberg previews is not possible and we need to load these styles on every Storybook page/preview perhaps that is a suitable compromise.

**Comment by derekshirk** [comment]
I have attempted to add the Gutenberg style import to .`storybook/preview.js` _before_ our `src/index.scss import`. However, to my surprise it appears to have no impact on these styles being loaded after `main.css

```js
import '@wordpress/block-library/build-style/style.css';
import 'focus-visible';
import '../src/index.scss';
import './preview.scss';
```

![Screen Shot 2020-06-10 at 4 33 37 PM](https://user-images.githubusercontent.com/1427548/84328928-3261a600-ab38-11ea-9cc6-2eb8171456fa.png)

🤔

**Comment by tylersticka** [comment]
Our current `main.scss` is generated from `src/index.scss`.

Have you tried adding a `src/with-wordpress-block-library.scss` file that imports the index and the dependency?

Then we could import that in `preview.js`.

I don't know if that's the _right_ solution, just trying to eliminate variables that could be causing things to output in an odd order.

**Comment by spaceninja** [comment]
@tylersticka I'm closing this — The PR was merged, it was moved to the "Done" column and the bug is no longer visible, so I think it was left open by mistake.
