### ISSUE TITLE
Rename main branch

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#794]
We should rename our primary branch to something other than `master`.

It's unclear what impact this would have on Netlify, npm, etc.

Here is a helpful guide: https://github.com/chancancode/branch-rename/

**Comment by tylersticka** [comment]
I tested this process on a small personal project that automatically deploys to Netlify, and it was straightforward. Here are the steps I took.

## 1. Locally

1. `git checkout master` (switch to `master`)
1. `git pull` (pull the latest)
1. `git status` (double check no outstanding changes)
1. `git checkout -b main` (start a new branch called `main`)
1. `git push -u origin main` (push this branch to GitHub)

**Risk:** None. The `master` branch is intact at this point.

## 2. Netlify

1. Opened [Netlify](https://app.netlify.com) and selected the project.
1. Navigated to Settings ▸ Build and Deploy ▸ Deploy Contexts.
1. Selected "Edit Settings."
1. Changed "Production Branch" to "main."
1. Selected "Save."

**Risk:** None. Even if there's an issue with `main`, the last successful deploy will remain live (regardless of its branch of origin).

## 3. GitHub

1. Navigated to the project repository.
1. Navigated to Settings ▸ Branches
1. Under "Default branch," changed to "main," selected "update" and agreed to any confirmations along the way. (**Note:** We probably won't do this step quite yet for this project because it is a work in progress.)

**Risk:** Low. It's possible that existing PRs will need to be closed and re-opened to target the new branch.

## (Optional) Cleanup

After completing these steps, `master` was still hanging around. There isn't any harm in keeping it around "just in case," but eventually you can remove it:

- **Locally:** `git branch -D master`
- **Netlify:** Navigate to the same "Deploy Contexts" settings area and remove `master` from the "individual branches" section.
- **GitHub:** Navigate to the "Code" tab for the repository, then select the branches summary (example: "5 Branches"), then select the 🗑 icon next to `master`.

**Risk:** Medium. At this point we _are_ destroying a branch, but hopefully we won't do any of this until we're sure that everything's working as expected.

**Comment by spaceninja** [comment]
Done!
